### ISSUE TITLE
Does hubicfuse work with encfs?

### ISSUE THREAD

**Issue by cortopy** [TurboGit/hubicfuse#102]
I'm just trying hubicfuse and it works great. However. for some reason, I can't get encfs to work with it. I can mount dirs with encfs and touch files, but can't edit, write or copy files

I get the following error: 

```
write error: Input/output error
```

Apart from encfs everything else works fine. Could it be some mount options I'm not getting right?

**Comment by P-p-H-d** [comment]
I also get this issue.
I think it is due to https://github.com/TurboGit/hubicfuse/issues/101

**Comment by TurboGit** [comment]
Since #101 is fixed I'm closing. Please reopen if needed.
