### ISSUE TITLE
failed: Input/output error (5)

### ISSUE THREAD

**Issue by hregis** [TurboGit/hubicfuse#103]
Hi,
i try to copy files with "rsync" (same problem with "cp"),
the directories are created, but for the files, i have this error message :

rsync: mkstemp "/mnt/hubic/default/my_directory/my_file.tar.xz.V52w1W" failed: Input/output error (5)

I guess it's a problem of write access? do you have a solution ?

Thank you

**Comment by Fraifrai** [comment]
Hi, when you create your config file, do not just press enter for acces rights but copy the proposed letters.

**Comment by hregis** [comment]
@Fraifrai 
Hello
yes that's what I did. In doubt I started again and same result. Looking at the rights Hubic, I feel it does not take into account write permissions.

**Comment by Thieume** [comment]
Hello.
Same problem for me too.
I can create directories under "default" directory, but I can't create files (even with my simple account or with root on my PC).
When I launched the hubic_token script, I have copied the letter proposed.

`[root@i5 default]# 
[root@i5 default]# pwd
/mnt/hubic/default
[root@i5 default]# ls
Documents  Images  Videos
[root@i5 default]# mkdir johnny
[root@i5 default]# ls
Documents  Images  johnny  Videos
[root@i5 default]# touch abc.txt
touch: impossible de faire un touch « abc.txt »: Erreur d'entrée/sortie
[root@i5 default]# 
`

**Comment by mrgoodfriend** [comment]
After an OS reinstall and so a hubicfuse update, I have the "cp: cannot create regular file ‘/mnt/hubic/default/x’: Input/output error" just when doing a cp.

After adding the -f parameter when launching hubicfuse the following error appears : 
"exit 1: cfs_open cannot open temp_file=[/tmp/hubicfuse/.cloudfuse_.default.x] err=2:No such file or directory"

It appears that hubicfuse directory was not present in /tmp
After creating it, no more problem with cp.

Hope it will help to solve the issue.

**Comment by hregis** [comment]
it's ok for me with the last version, thanks

**Comment by MeiRos** [comment]
Than you mrgoodfriend. I had the same problem before I read your comment.
