### ISSUE TITLE
Installin issue

### ISSUE THREAD

**Issue by byman64** [TurboGit/hubicfuse#105]
I was installing hubicfuse on ubuntu server 15.04 and I got an 2 errors on
-  ./configure 
-  make

./configure error: 
**_START**_**********************************************************
'Unable to find libmagic headers.  Please make sure header files are installed.'
**_END**_**********************************************************

Fixed with 
apt-get install libmagic-dev

make error
**_START**_**********************************************************
root@ns352475:/tmp/hubicfuse-master# make
gcc -g -O2 -I/usr/include/libxml2   -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse   -I/usr/include/json-c  -o hubicfuse cloudfsapi.c cloudfuse.c commonfs.c -lxml2  -lcurl  -lfuse -pthread  -lssl -lcrypto  -ljson-c  -lmagic
commonfs.c: In function ‘get_time_as_string’:
commonfs.c:100:3: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
   sprintf(nsec_str, "%d", nsec);
   ^
commonfs.c: In function ‘get_file_path_from_fd’:
commonfs.c:217:3: warning: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Wunused-result]
   readlink(proc_path, path, size_path - 1);
   ^
**_END**_**********************************************************

By the way I have my hubicfuse command but it does not find the .hubicfuse file

I have a .cloudfuse from my previus hubifuse on my ubuntu 14.04 where hubicfuse workedfine.

Now I am running ubuntu 15.04 and I cannot understand why hubicfuse does not fine my .hubicfuse with inside all variables.

**_START**_*************************************************************
root@host7:~# hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
Unable to determine client_id, client_secret or refresh_token.

These can be set either as mount options or in a file named /root/.hubicfuse

  client_id=[App's id]
  client_secret=[App's secret]
  refresh_token=[Get it running hubic_token]
The following settings are optional:

  cache_timeout=[Seconds for directory caching, default 600]
  verify_ssl=[false to disable SSL cert verification]
  segment_size=[Size to use when creating DLOs, default 1073741824]
  segment_above=[File size at which to use segments, defult 2147483648]
  storage_url=[Storage URL for other tenant to view container]
  container=[Public container to view of tenant specified by storage_url]
  temp_dir=[Directory to store temp files]
  get_extended_metadata=[true to enable download of utime, chmod, chown file attributes (but slower)]
  curl_verbose=[true to debug info on curl requests (lots of output)]
  curl_progress_state=[true to enable progress callback enabled. Mostly used for debugging]
  cache_statfs_timeout=[number of seconds to cache requests to statfs (cloud statistics), 0 for no cache]
  debug_level=[0 to 2, 0 for minimal verbose debugging. No debug if -d or -f option is not provided.]
  enable_chmod=[true to enable chmod support on fuse]
  enable_chown=[true to enable chown support on fuse]
root@host7:~#
**_END**_**********************************************************

I am working with root and if I type /root/.hubicfuse I see the following
username=mymail@onmydomain.com
password=mypassword
client_id=api_hubic_w3Nu7oA34ryPMHA3aTlcoHs8MdIWnBHO
client_secret=AC0IzjuIkvIWuI1JBS4TUlD54Q6Q2hY6VOGRiTS9u2aFXcYFb5WV952O3FCxbIs5
redirect_uri=http://localhost

 here the error

Please let me know if you need more details

**Comment by Overbull** [comment]
till I know, the minimun configuration that you need to put into .hubicfuse file are

```
client_id=*****************************
client_secret=**************************
refresh_token=**********************
temp_dir = a temp dir in your system 

```
so try to put this information into that file.

umount and mount again and try.

**Comment by TurboGit** [comment]
The temp_dir is not mandatory. I don't use it. This is only needed if your /tmp is not big enough for uploaded files.

**Comment by TurboGit** [comment]
@byman64 : you are using the old authentification method, this is not supported by HubiC since a long time now.

**Comment by TurboGit** [comment]
@byman64 you're missing the refresh_token and you can remove username, password and redirect_url. It looks like you are using the old authentication method!

**Comment by TurboGit** [comment]
No reply.
