### ISSUE TITLE
Hard links? (incremental backup)

### ISSUE THREAD

**Issue by balat** [TurboGit/hubicfuse#106]
Hello,

I'm trying to use hubicfuse to create an incremental backup with rsync.
Do you know if it is possible to do that?
My first attempts failed because existing files are not hard-linked but copied ...
It seems hubicfuse does not support hard links?
$ ln aaa bbb
ln: failed to create hard link 'bbb' => 'aaa': Function not implemented

Also, I have many errors like
rsync: failed to set times on "/mnt/hubic/default/blah": Function not implemented (38)

Do you have any idea on how to do an incremental backup on hubic?
Tell me if you need more information.
Thanks!
Vincent

**Comment by TurboGit** [comment]
Which version are you using? Soft links are supported, I don't know for hard links, I'm not even sure this is possible in fact.

**Comment by dplamp** [comment]
Hi, I have been facing similar issues with rsync, as detailed in #104. I just left it aside for now, because persistent errors and lack of support...

**Comment by balat** [comment]
Thank you for your answers.
Any hint from the developers?

**Comment by TurboGit** [comment]
There is nothing like hard-links on Hubic infrastructure. That's also why rsync cannot be used reliably on hubic.
