### ISSUE TITLE
Patch for issue with large file (up to 2GiB) on 32 bit OS 

### ISSUE THREAD

**Issue by bronco0** [TurboGit/hubicfuse#110]
Hi,

**This patch must be tested on 64 bit OS !!**

In cloudfsapi.c lines [639](https://github.com/TurboGit/hubicfuse/blob/master/cloudfsapi.c#L639) and [973](https://github.com/TurboGit/hubicfuse/blob/master/cloudfsapi.c#L973) replace
`long flen;`
by
`off_t flen;`

In cloudfsapi.c line [485](https://github.com/TurboGit/hubicfuse/blob/master/cloudfsapi.c#L485) replace ([See libcurl API doc](http://curl.haxx.se/libcurl/c/CURLOPT_INFILESIZE.html))
`curl_easy_setopt(curl, CURLOPT_INFILESIZE, file_size);`
by
`curl_easy_setopt(curl, CURLOPT_INFILESIZE_LARGE, file_size);`

In cloudfsapi.c line [1016](https://github.com/TurboGit/hubicfuse/blob/master/cloudfsapi.c#L1016) replace 
`snprintf(manifest, MAX_URL_SIZE, "%s_segments/%s/%s/%ld/%ld/",`
by
`snprintf(manifest, MAX_URL_SIZE, "%s_segments/%s/%s/%lld/%ld/",`
for -Wformat error.

In commonfs.c line [100](https://github.com/TurboGit/hubicfuse/blob/master/commonfs.c#L100) replace
`sprintf(nsec_str, "%d", nsec);`
by
`sprintf(nsec_str, "%ld", nsec);`
for -Wformat error.

**No need to compile with the option -D_FILE_OFFSET_BITS=64**

Thanks

**Comment by dan-cristian** [comment]
Will include this, thanks.

**Comment by TurboGit** [comment]
Closing, all those should be fixed now.
