### ISSUE TITLE
Failed to authenticate.

### ISSUE THREAD

**Issue by dannyb2100** [TurboGit/hubicfuse#111]
Hey,

Followed the guide, everything works up to this point. Tried a clean clone/download and so forth. Nothing seems to be work? Any idea, logging or input?

Here is what your app needs to connect to hubiC:
client_id=lettersandnumbers
client_secret=lettersandnumbers
refresh_token=lettersandnumbers
[danny@localhost hubicfuse]$ hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
Failed to authenticate.
[danny@localhost hubicfuse]$ sudo ./hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
Failed to authenticate.
[danny@localhost hubicfuse]$

**Comment by TurboGit** [comment]
How was the refresh_token generated?

**Comment by dannyb2100** [comment]
Via the hubic_token script.

**Comment by superwebium** [comment]
Hello,

Same thing for me, installed twice, and "failed to authenticate" when trying to mount...

Refresh_token generated by ./hubic_token script.

**Comment by TurboGit** [comment]
Looks like a FAQ at this stage :)

When running hubic_token you *need* to enter the values proposed if you agree (or change them). Just pressing enter does zero permission, hence the error!

**Comment by superwebium** [comment]
Sorry, my fault !

I just hit "enter" during hubic_token procedure, i relaunch it with typing r, rw, etc and now it works...!

**Comment by Fraifrai** [comment]
Shouldn't the script use defaults values when just pressing enter and a specific value like "0" be used to set "notuhing" ?

**Comment by dannyb2100** [comment]
Also my bad!! 
I was used to the proposed values being defaulted when nothing is entered! Works now :)
