### ISSUE TITLE
copying large files without split, AKA (_segment_dir)

### ISSUE THREAD

**Issue by Overbull** [TurboGit/hubicfuse#113]
Hi! First of all, I'm very noob using GitHub(Sorry TurboGit) so I apologize for it, I'm looked before if someone did the same question but finally I'm not sure is if possible or not to copy large files to hubic without split.

I tested a few options but without right results, In the cases that the file apparently was copied without split, few minutes later or after copy a new file, the file cannot be displayed in hubic, so i think that was removed automatically.

So, If is possible. How I need to configure de .hubicfuse configuration file?  and Wich conf i need to launch hubicfuse command.

> SO. Debian Jessie 8.3 Kernel 64Bit
> FUSE library version: 2.9.4
> fusermount version: 2.9.4
> using FUSE kernel interface version 7.19

.hubicfuse file
```
***
***
***
cache_timeout = 600
temp_dir =/home/user/temp

get_extended_metadata = true
curl_verbose = false
curl_progress_state = true
cache_statfs_timeout = 15
debug_level = 0
enable_chmod = false
enable_chown = false
segment_size=4294967296
segment_above=10737418240
```

Many Thanks
OverBull

**Comment by TurboGit** [comment]
Hey! You can't use TurboGit that's my Git nick name :)

I'll let the expert of large-file response. But to me your .hubicfuse looks ok. Not sure why the files gets segmented. I must say that I do not send large file to hubic myself :)

**Comment by Overbull** [comment]
jajajaja! I'm sorry I was talking about Github ;-)

**Comment by dan-cristian** [comment]
A file uploaded to hubic will be segmented if the file size is larger than option segment_above. 
I think you have the segment_above size way to large that's why you don't see the uploaded files.

You can increase the segment_above I think up to max 5 GB if you want least no of files to be segmented. An upload of a file larger than 5 GB will fail.

Parameter segment_size sets the size of each segment that will be uploaded. I think the hubic standard segment_size is 100 MB.

This is standard swift feature and should work well also in your case, it's actually an advantage to segment large files as the chance to get an error while working with smaller segments is reduced compared with very large files.

**Comment by Overbull** [comment]
Hi Dan, by the way or in my case if I don't configure segment_size or segment_above in the .hubicfuse, the system frangmented files in 1Gb each.

I'll try to assing segment_above with the teorical openstack limit of 5Gb to have the possiblity to split only the files up to this size.

**Comment by Overbull** [comment]
Hi Again, the tests was succesfully. Now all files upper to 5Gb split into 1Gb files (segment_dir) have been copied to hubic and the files up to 5Gb size, have been copied without split. 

So if the problem is the theorical 5Gb size limit by openstack the issue can be closed.

Many thanks

P.S. Maybe a little appointment in the readme file o whatever,  could be a good decision for the future.

**Comment by TurboGit** [comment]
I have added a note about the 5Gb size limit in the README and I have added a test into hubicfuse itself.

**Comment by D4void** [comment]
@Overbull 
I discover your post. I am trying to upload large file with hubicfuse.
I will open an new issue but which value did you put on segment_size and segment_above to upload a file greater than 5GB ?
I try to upload a file of 7GB+ . I splitted it in 2 files of less than 5GB.
When I try to copy to hubic , I only have 2043105280 bytes copied for both files with the values below in my .hubicfuse :
segment_size=1073741824
segment_above=5368709120

In my source dir, ls of files give:
file1 is 4294967296  bytes
file2 is 2966032682  bytes
