### ISSUE TITLE
Files doesn't appear on hubic web interfaces

### ISSUE THREAD

**Issue by stylersnico** [TurboGit/hubicfuse#114]
Hi,

Everything seems to work perfectly but I don't see anything on the Hubic interfaces, folders included. Any idea?

**Comment by romanrm** [comment]
Do you upload files with hubicfuse into the folder called "default" (which exists from the start)?

**Comment by stylersnico** [comment]
No, a root folder directly, I've just understood my error when I have see this default folder both on the server and hubic webinterface.

Thanks @romanrm :+1:
