### ISSUE TITLE
What's the maximum split size for this soft?

### ISSUE THREAD

**Issue by stylersnico** [TurboGit/hubicfuse#115]
Hi,

I just want to know what's the maximum filesize for this soft.

I can't upload a 6-7Gb file but it works when splitted in 100Mb files.

Any idead?

**Comment by dan-cristian** [comment]
5 GB, an openstack limitation by design, not a hubicfuse one.

Don't we have a better place to post such requests for information/questions?

**Comment by stylersnico** [comment]
I don't but the soft even fails after some file upload.

The mounted drive simply hang and does nothing

**Comment by TurboGit** [comment]
I have added a note about the 5Gb size limit in the README and I have added a test into hubicfuse itself.
