### ISSUE TITLE
modprobe fuse on Debian 8

### ISSUE THREAD

**Issue by jenga201** [TurboGit/hubicfuse#117]
I'm getting an error when trying to mount;
~$ hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
fuse: device not found, try 'modprobe fuse' first
~$ sudo modprobe fuse
modprobe: ERROR: could not insert 'fuse': Unknown symbol in module, or unknown parameter (see dmesg)
~$ ls -lah /dev/fuse
crw-rw-rw- 1 root root 10, 229 Jan 26 09:45 /dev/fuse

I compiled hubicfuse without issue.

These packages are installed;
gcc make curl libfuse-dev pkg-config \
libcurl4-openssl-dev libxml2-dev libssl-dev libjson-c-dev \
libmagic-dev fuse makedev

Kernel version.
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux

From what I see, to run modprobe fuse requires linux kernel 3.2. This doesn't exist in the apt repo.

Is there anything I can do without upgrading kernel versions to fix this?

**Comment by TurboGit** [comment]
I don't have a Debian 8 box to test, but just to be sure have you installed the fuse package?

**Comment by jenga201** [comment]
Yeah, fuse is installed.

~$ sudo apt-get install fuse libcurl3 libssl-dev libxml2
Reading package lists... Done
Building dependency tree
Reading state information... Done
libxml2 is already the newest version.
libxml2 set to manually installed.
libssl-dev is already the newest version.
libcurl3 is already the newest version.
libcurl3 set to manually installed.
fuse is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by TurboGit** [comment]
I'm sure we had reports here from people using Jessie. Was this working before? If the kernel has been updated have you recompiled hubicfuse?

> ~$ sudo modprobe fuse
> modprobe: ERROR: could not insert 'fuse': Unknown symbol in module, or unknown parameter (see dmesg)

This is definitely the error. Looks like fuse module is not compatible with your kernel. Until this is solved I suppose there is way to have hubicfuse running.

**Comment by jenga201** [comment]
That's what I thought.
I haven't upgraded the kernel.  Usually compatible kernels are in the apt repo, but only 3.16 exists.

Guess its time to find out how to upgrade to 3.2

**Comment by TurboGit** [comment]
I'm not sure to follow, 3.16 is more recent that 3.2?

**Comment by romanrm** [comment]
What output do you get from `modinfo fuse`?

**Comment by jenga201** [comment]
~$ sudo modinfo fuse
[sudo] password for jenga:
filename:       /lib/modules/3.16.0-4-amd64/kernel/fs/fuse/fuse.ko
alias:          devname:fuse
alias:          char-major-10-229
alias:          fs-fuseblk
alias:          fs-fuse
license:        GPL
description:    Filesystem in Userspace
author:         Miklos Szeredi <miklos@szeredi.hu>
alias:          fs-fusectl
depends:
intree:         Y
vermagic:       3.16.0-4-amd64 SMP mod_unload modversions
parm:           max_user_bgreq:Global limit for the maximum number of backgrounded requests an unprivileged user can set (uint)
parm:           max_user_congthresh:Global limit for the maximum congestion threshold an unprivileged user can set (uint)

**Comment by nashe** [comment]
Got exactly the same problem tonight, with Jessie and using fuse for the first time. I just had to reboot the box and everything is working as expected now. It's definitely a bug related to the fuse package.

The performance is as announced: `268435456 bytes (268 MB) copied, 34.9166 s, 7.7 MB/s`. Kudos to TurboGit and to all the contributors for this module!

**Comment by jenga201** [comment]
Since when is rebooting a legit troubleshooting technique?

Well, it worked.  I can now mount hubic.

Thanks

**Comment by nashe** [comment]
I don't know, but everytime I have a trouble with some kernel modules… that's the last thing to try before suicide, I agree. 

More seriously, I think that's because the version of the currently loaded kernel is not exactly the same that the one with which the fuse package dependencies are resolved (strange sentence…), since you have to reboot to effectively use the new kernel. Did you installed an kernel update since you last reboot?
