### ISSUE TITLE
Redirection domain

### ISSUE THREAD

**Issue by skerit** [TurboGit/hubicfuse#118]
So I can't create an application on hubic without an HTTPS redirection domain... Is there any other way of getting the required keys?

**Comment by Fraifrai** [comment]
You can specify any existing or unexisting domain. It's just a key.

**Comment by Vebryn** [comment]
Hi,

You can put http::/localhost/. If an error says that application name is invalid, change your last name.

**Comment by TurboGit** [comment]
Nothing to do, closing.
