### ISSUE TITLE
make (warning) source 22.02.16

### ISSUE THREAD

**Issue by c3ph3us** [TurboGit/hubicfuse#119]
gcc -g -O2 -I/usr/include/libxml2   -D_FILE_OFFSET_BITS=64 -I/usr/include/fuse   -I/usr/include/json-c  -o hubicfuse cloudfsapi.c cloudfuse.c commonfs.c -lxml2  -lcurl  -lfuse -pthread  -lssl -lcrypto  -ljson-c  -lmagic 
commonfs.c: In function ‘get_time_as_string’:
commonfs.c:100:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
   sprintf(nsec_str, "%d", nsec);
                     ^
commonfs.c: In function ‘get_file_path_from_fd’:
commonfs.c:212:3: warning: ignoring return value of ‘readlink’, declared with attribute warn_unused_result [-Wunused-result]
   readlink(proc_path, path, size_path - 1);

**Comment by TurboGit** [comment]
Should be fixed. Can you test again?
