### ISSUE TITLE
A segment cannot be larger than 5Gb

### ISSUE THREAD

**Issue by sioban** [TurboGit/hubicfuse#122]
Hi,

I cannot use anymore Hubicfuse, I get the answer "A segment cannot be larger than 5Gb" even with no parameters.

```
# hubicfuse --help
A segment cannot be larger than 5Gb
```

The only thing that come in mind is that I've updated my kernel yesterday (4.3.3 to 4.3.5).
I've tried recompiling / reinstalling hubicfuse with no success.

Any idea ?

**Comment by TurboGit** [comment]
Do you have a segment size specified in your ~/.hubicfuse ?

A recent check (Feb 2 2016) has been added into hubicfuse to detect segment larger than what is supported on HubiC.

**Comment by sioban** [comment]
nope I have nothing specificed
Should I ?

**Comment by TurboGit** [comment]
Well you have something specified in .hubicfuse, right? At least client_id, client_secret and refresh_token?

**Comment by sioban** [comment]
Yes I have these one.
Until the reboot of the server because of new kernel, hubicfuse was working fine.

**Comment by TurboGit** [comment]
This is really strange! You haven't change the hubicfuse source then? I would have say that you should recompile hubicfuse after a kernel change but you've already done that! 

Is that a 32bit or 64bit OS?

You may want to define segment_size and segment_above in your .hubicfuse. Something like:

segment_size=1073741824
segment_above=2147483000

Does it works? If yes, can you test with:

segment_above=2147483647

Thanks.

**Comment by sioban** [comment]
32bits

**Comment by sioban** [comment]
can I produce some logs to have something more verbose ?

**Comment by TurboGit** [comment]
Have you tried first the segment_size and segment_above proposed above?

**Comment by sioban** [comment]
yes but it fails

**Comment by TurboGit** [comment]
Same error message?

So, try running hubicfuse with -d (debug) option:

$ hubicfuse -d /your/mount/point

**Comment by sioban** [comment]
# hubicfuse -d /mnt/hubic
A segment cannot be larger than 5Gb

Does it put logs somewhere or it should be on screen ?

**Comment by TurboGit** [comment]
It should be on the console, so the error is very very early when reading the parameters. Let me review the code!

**Comment by TurboGit** [comment]
I've just pushed a quick fix. Can you try again?

**Comment by sioban** [comment]
it solved the problem.
Should I remove segment_size and segment_above ?

**Comment by TurboGit** [comment]
Yes, you should remove them it and keep the default as it was before.
