### ISSUE TITLE
time of files synced to hubic, get current system time

### ISSUE THREAD

**Issue by Nihim** [TurboGit/hubicfuse#123]
I have tried lftp with multiple of different flags and rsync. No matter what the files synced into hubic get their time from when the transfer runs.

Is there a way to avoid that or that is just how hubic / fuse works?

Cheers

**Comment by dan-cristian** [comment]
see hubicfuse.sample file, you should use option get_extended_metadata=true
to enable proper timestamps.

**Comment by Nihim** [comment]
Ah thank you very much, should have paid closer attention on the main page than re -reading lftp / rsync man and googling like mad.

Doing ls inside the hubic dir makes ls show like it's frozen. I am guessing that is due to hubicfuse getting the time of all the contents inside? which is several T.

Also something offtopic for anyone that can answer. I have a bunch of questions about hubicfuse and last time I was suggested to use one ticket per question. Should I really do that, should I add them in one ticket called "questions X,Y,Z" or is there a better way via email or something?

**Comment by dan-cristian** [comment]
With that option enabled hubicfuse will do an additional HTTP GET request for each file, but will only retrieve the headers, not full content.

However if you have many files in a folder it will take quite a while, as I noticed Hubic is sometimes very slow on accepting a connection (GET or PUT/POST).

 

Not sure about the 2nd question, I guess is better to use Wiki for this and create an FAQ, rather than opening issues – my view.

**Comment by Nihim** [comment]
ok will try to do that and at worse if it is too random I 'll try to remove stuff from it, till it is atleast useful.

So now ls -l shows the correct time **but** if I access the same files via ftp, I see instead the time they were copied into hubic. So am I right to assume that if the "client" doesn't specifically request the "real" times it won't show them?

**Comment by dan-cristian** [comment]
Not sure why ftp does that, I have not tested. try to experiment yourself
using "stat file" command and see what value time fields have.

**Comment by TurboGit** [comment]
Le vendredi 18 mars 2016 à 03:14 -0700, Nihim a écrit :
> Also something offtopic for anyone that can answer. I have a bunch of
> questions about hubicfuse and last time I was suggested to use one
> ticket per question. 

Yes better to do that or group them in the same ticket if *very*
related.

-- 
  Pascal Obry /  Magny Les Hameaux (78)

  The best way to travel is by means of imagination

  http://v2p.fr.eu.org
  http://www.obry.net

  gpg --keyserver keys.gnupg.net --recv-key F949BD3B

**Comment by Nihim** [comment]
All will be for the same dir!!

-Filezilla
11:03:15	Command:	stat file
11:03:15	Response:	213-Status follows:
11:03:15	Response:	213 End of status

-lftp
quote stat -l
213-Status follows:
drwxr-xr-x    2 ftp      ftp             0 Mar 19 12:47 .
drwxr-xr-x    2 ftp      ftp             0 Mar 19 12:46 ..
-rw-rw-rw-    1 ftp      ftp      131269084 Feb 01 05:38 file - 01 [400p].mkv
-rw-rw-rw-    1 ftp      ftp      251519929 Feb 01 05:38 file - 01 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      476694952 Feb 01 05:38 file - 01v2 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      200393213 Feb 01 05:38 file - 01v2 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      299993934 Feb 01 05:39 file - 01v2 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      489073402 Feb 01 05:39 file - 02 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      204778482 Feb 01 05:39 file - 02 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      307619405 Feb 01 05:39 file - 02 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      479650256 Feb 01 05:39 file - 03 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      198938208 Feb 01 05:39 file - 03 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      297174738 Feb 01 05:39 file - 03 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      491616235 Feb 01 05:40 file - 04 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      206124630 Feb 01 05:40 file - 04 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      308901451 Feb 01 05:40 file - 04 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      490855819 Feb 04 22:34 file - 05 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      205940090 Feb 04 22:35 file - 05 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      308651006 Feb 04 22:35 file - 05 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      489886259 Mar 18 11:00 file - 06 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      204029021 Mar 18 10:57 file - 06 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      306997748 Mar 18 10:59 file - 06 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      491018936 Mar 18 11:01 file - 07 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      206059396 Mar 18 10:58 file - 07 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      308840098 Mar 18 11:02 file - 07 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      488644885 Mar 18 11:04 file - 08 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      205349397 Mar 18 11:02 file - 08 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      307532298 Mar 18 11:13 file - 08 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      492589400 Mar 18 11:13 file - 09 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      206559864 Mar 18 11:05 file - 09 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      309757657 Mar 18 11:14 file - 09 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      487374769 Mar 18 11:14 file - 09.5 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      204520892 Mar 18 11:15 file - 09.5 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      306605340 Mar 18 11:09 file - 09.5 [720p].mkv
-rw-rw-rw-    1 ftp      ftp      493666385 Mar 18 11:12 file - 10 [1080p].mkv
-rw-rw-rw-    1 ftp      ftp      207601947 Mar 18 11:10 file - 10 [480p].mkv
-rw-rw-rw-    1 ftp      ftp      310650381 Mar 18 11:11 file - 10 [720p].mkv
213 End of status

-SSH
ls -ltr
total 11110312
-rw-rw-rw- 1 nihim nihim 131269084 Jan  7 19:35 file - 01 [400p].mkv
-rw-rw-rw- 1 nihim nihim 251519929 Jan  7 19:36 file - 01 [720p].mkv
-rw-rw-rw- 1 nihim nihim 200393213 Jan  9 02:05 file - 01v2 [480p].mkv
-rw-rw-rw- 1 nihim nihim 299993934 Jan  9 02:05 file - 01v2 [720p].mkv
-rw-rw-rw- 1 nihim nihim 476694952 Jan  9 02:05 file - 01v2 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 204778482 Jan 14 23:02 file - 02 [480p].mkv
-rw-rw-rw- 1 nihim nihim 307619405 Jan 14 23:02 file - 02 [720p].mkv
-rw-rw-rw- 1 nihim nihim 489073402 Jan 14 23:03 file - 02 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 297174738 Jan 21 22:02 file - 03 [720p].mkv
-rw-rw-rw- 1 nihim nihim 198938208 Jan 21 22:03 file - 03 [480p].mkv
-rw-rw-rw- 1 nihim nihim 479650256 Jan 21 22:03 file - 03 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 206124630 Jan 28 21:48 file - 04 [480p].mkv
-rw-rw-rw- 1 nihim nihim 308901451 Jan 28 21:49 file - 04 [720p].mkv
-rw-rw-rw- 1 nihim nihim 491616235 Jan 28 21:50 file - 04 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 490855819 Feb  4 21:51 file - 05 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 308651006 Feb  4 21:51 file - 05 [720p].mkv
-rw-rw-rw- 1 nihim nihim 205940090 Feb  4 21:52 file - 05 [480p].mkv
-rw-rw-rw- 1 nihim nihim 306997748 Feb 11 21:49 file - 06 [720p].mkv
-rw-rw-rw- 1 nihim nihim 204029021 Feb 11 21:49 file - 06 [480p].mkv
-rw-rw-rw- 1 nihim nihim 489886259 Feb 11 21:52 file - 06 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 206059396 Feb 18 21:54 file - 07 [480p].mkv
-rw-rw-rw- 1 nihim nihim 491018936 Feb 18 21:55 file - 07 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 308840098 Feb 18 21:55 file - 07 [720p].mkv
-rw-rw-rw- 1 nihim nihim 205349397 Feb 26 04:53 file - 08 [480p].mkv
-rw-rw-rw- 1 nihim nihim 488644885 Feb 26 04:56 file - 08 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 309757657 Mar  3 21:51 file - 09 [720p].mkv
-rw-rw-rw- 1 nihim nihim 206559864 Mar  3 21:52 file - 09 [480p].mkv
-rw-rw-rw- 1 nihim nihim 492589400 Mar  3 21:53 file - 09 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 204520892 Mar 11 19:15 file - 09.5 [480p].mkv
-rw-rw-rw- 1 nihim nihim 306605340 Mar 11 19:18 file - 09.5 [720p].mkv
-rw-rw-rw- 1 nihim nihim 487374769 Mar 11 19:21 file - 09.5 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 310650381 Mar 18 05:27 file - 10 [720p].mkv
-rw-rw-rw- 1 nihim nihim 207601947 Mar 18 05:27 file - 10 [480p].mkv
-rw-rw-rw- 1 nihim nihim 493666385 Mar 18 05:28 file - 10 [1080p].mkv
-rw-rw-rw- 1 nihim nihim 307532298 Mar 18 11:06 file - 08 [720p].mkv

part of stat 
  File: file - 08 [480p].mkv’
Access: 2016-02-26 04:53:57.000000000 +0100
Modify: 2016-02-26 04:53:57.000000000 +0100
Change: 2016-03-18 11:02:32.528367151 +0100
 Birth: -
  File: file - 08 [720p].mkv’
Access: 2016-03-18 11:06:01.000000000 +0100
Modify: 2016-03-18 11:06:01.000000000 +0100
Change: 2016-03-18 11:06:01.000000000 +0100
 Birth: -
  File: file - 09 [1080p].mkv’
Access: 2016-03-03 21:53:27.000000000 +0100
Modify: 2016-03-03 21:53:27.000000000 +0100
Change: 2016-03-18 11:08:09.704355349 +0100
 Birth: -
  File: file - 09 [480p].mkv’
Access: 2016-03-03 21:52:54.000000000 +0100
Modify: 2016-03-03 21:52:54.000000000 +0100
Change: 2016-03-18 11:05:13.820823054 +0100
 Birth: -
  File: file - 09.5 [1080p].mkv’
Access: 2016-03-11 19:21:53.000000000 +0100
Modify: 2016-03-11 19:21:53.000000000 +0100
Change: 2016-03-18 11:10:30.585178609 +0100
 Birth: -
  File: file - 09.5 [480p].mkv’
Access: 2016-03-11 19:15:13.000000000 +0100
Modify: 2016-03-11 19:15:13.000000000 +0100
Change: 2016-03-18 11:07:38.759100152 +0100
 Birth: -

So I am guessing the ftp is getting the change time instead of time modified.
Both clients lftp & filezilla get it wrong.

**Comment by dan-cristian** [comment]
Change timestamp is set by hubic after a file is changed in the cloud, I
think this is "as per design" behavior and should stay as it is currently
implemented.

**Comment by Nihim** [comment]
Ah I see, thank you for confirming that. Would be nice if there was an option to disable that, but it is generally not a big problem.

**Comment by TurboGit** [comment]
nothing we can do, should have been closed long time ago.
