### ISSUE TITLE
mount: wrong fs type, bad option, bad superblock on hubicfuse

### ISSUE THREAD

**Issue by sbrl** [TurboGit/hubicfuse#125]
Hello,

I'm attempting to mount my hubic drive with hubicfuse, and I can do this with the following command:

```bash
hubicfuse /mnt/hubic -o sync_read,allow_other
```

....but if I try to do the same with an `/etc/fstab entry, it doesn't work and fails with this error:

```
mount: wrong fs type, bad option, bad superblock on hubicfuse,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

`dmesg | tail` doesn't help. Here's my `/etc/fstab` entry:

```bash
hubicfuse	/mnt/hubic	fuse	user,sync_read,allow_other	0	0
```

**Comment by TurboGit** [comment]
Strange, my fstab entry is:

hubicfuse	/mnt/hubic	fuse	noauto,noauto_cache,sync_read,user,allow_other	0	0

and works fine since years! Can you test it with this options to see if it makes a difference on your side?

Also, what is you disk fs type? I'm on ext4.

**Comment by sbrl** [comment]
Hrm. That entry doesn't work either:

```
sudo mount /mnt/hubic
mount: wrong fs type, bad option, bad superblock on hubicfuse,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.
```

and how do I find out what my fs type is? Nothing shows up with `sudo blkid` or `sudo fdisk -l`, because it's a 2014 OVH VPS.

**Comment by romanrm** [comment]
Those are OpenVZ, all sorts of kernel module requiring things (including FUSE) can go wrong on OpenVZ. Just add the hubicfuse line which works fine for you into /etc/rc.local. Or consider upgrading to a KVM VPS (such as the current OVH VPS-SSD).

**Comment by sbrl** [comment]
@romanrm Right. My plan is to migrate over to a new OVH VPS after my exams this summer. Thanks for your help!
