### ISSUE TITLE
FUSE for OVH public cloud storage

### ISSUE THREAD

**Issue by streamnsight** [TurboGit/hubicfuse#126]
Can this be used to mount bloc storage from the OVH Public Cloud ?

I got the impression from some OVH blog post a little while ago (sorry can't find the link) that Hubic was exactly the same things as the Public Cloud bloc storage.
However, credentials/auth process etc... seem quite different.

Any insight about this?
I'd like to try to mount public cloud bloc storage on bare metal hosts.
Thanks

**Comment by TurboGit** [comment]
If the credential is different then it won't be possible to mount. I cannot comment further as I'm not using the OVH Public Cloud. What is being this? Is that Openstack Swift? If so yes it can be made to work as this was what was used in HubiC in the early implementation. Note that hubicfuse was using the authentication for this implementation long time ago. Look in Git for the previous authentication implementation.

**Comment by TurboGit** [comment]
Nothing to do, closing.
