### ISSUE TITLE
segments and rsync-like software

### ISSUE THREAD

**Issue by romanrm** [TurboGit/hubicfuse#128]
Hello,

I'm trying out the segments support. Correct me if I'm wrong, but it looks like currently this can't work with rsync-like software. After a remount, in the mounted FS I see both the segmented file at its normal location (BUT WITH A ZERO SIZE), **and** a directory called originalname**_segments**. Needless to say on the next synchronization run the `rsync` program will totally wreck havoc to this weird setup, removing the _segments dir, and trying to reupload the zero-sized file.

Sooooo, is this how this is supposed to work currently? Or am I missing something, and there's a way to enable "masking" of the entire under-the-hood **_segments** implementation from the FS users?

**Comment by TurboGit** [comment]
No sure about this. Never tested using rsync. The zero size is reported where? If you do a 'ls' does the file is reported with the proper size?

Also, which hubicfuse version are you using?

**Comment by rgoe** [comment]
Hi,

i can confirm the situation described by romanrm.
Using fresh installed ubuntu 16.04.1 with hubicfuse git-cloned and build today (24/08/16).
Segmented files uploaded through hubic windows client (files are in /default, segments are in /default_segments - checked with swift explorer) are shown with size 0 when doing ls -la on the mounted fs (and also using mc etc.). I've attached two screenshots for one of those files. Let me know if I can give any other information and thanks for all your efforts regarding hubicfuse.
![file-ssh](https://cloud.githubusercontent.com/assets/21224499/17948615/d9757696-6a51-11e6-8de7-8e8fcdc54af2.jpg)
![file-swiftexplorer](https://cloud.githubusercontent.com/assets/21224499/17948616/d9759428-6a51-11e6-8de2-df86eb5c0d81.jpg)

**Comment by TurboGit** [comment]
At the moment rsync is indeed not supported as not something hubic can handle nicely.
