### ISSUE TITLE
problem to upload large file (> 5GB)

### ISSUE THREAD

**Issue by D4void** [TurboGit/hubicfuse#129]
Hello

I am trying to upload large file with hubicfuse.
I red some issues here and the README concerning the 5GB limit.

If I want to upload files with size between 2GB and 5 GB, which value can we use for "segment_size" and "segment_above" in the .hubicfuse ? 
My upload test all stopped with file size of 1,9 GB whatever the value I give to segment_above ...

I try to upload a file of 7GB+ . I splitted it in 2 files of less than 5GB.
In my source dir, ls of source files give me:
file1 is 4294967296  bytes
file2 is 2966032682  bytes 

When I try to copy to hubic , I only have 2043105280 bytes copied for both files with the values below in my .hubicfuse :
segment_size=1073741824
segment_above=5368709120
So the upload is not complete.

**Comment by TurboGit** [comment]
Sorry can't really help. I'm not using hubicfuse with such large file. As far as I remember some users have reported success with very large files.

Is that all the time? Have you tried many times? Maybe a connection issue?

**Comment by Overbull** [comment]
Hi, sorry for the delay, I didn't more test with the file size limit, for me the segment_above is 

segment_above=4294967290

for segment_size I always use hubicfuse default, so no segment_size is configured on .hubicfuse file ,other configurations do wrongs uploads(Time outs) 

So, please try to remove segment_size from .hubicfuse file and try to put the segment_above near a value to 5Gb size and test it.

**Comment by TurboGit** [comment]
No answer from OP, closing.
