### ISSUE TITLE
Cannot write files, only directories

### ISSUE THREAD

**Issue by Spooky4672** [TurboGit/hubicfuse#130]
Hi,

I have mounted my hubic storage by following this tutorial (in french) : http://phil.writesthisblog.com/hubic-debian/, on my Odroid XU4 with Armbian (jessie). The fuse module is loaded.

I cannot use dd, cp or touch but I can create and remove directories.
Everytime I get IO error.

**Comment by Spooky4672** [comment]
I had specified a temp directory in the .hubicfuse config file, but had not created it ...

**Comment by TurboGit** [comment]
:)
