### ISSUE TITLE
fail to authenticate

### ISSUE THREAD

**Issue by OrkaEdison** [TurboGit/hubicfuse#133]
`$ hubicfuse -d /home/Documents -o noauto_cache,sync_read
!!! Authenticating... (client_id = '')
!!! HUBIC AUTH_URL (req token) result: '<?xml version="1.0" encoding="utf-8"?>
<?modxslt-stylesheet type="text/xsl" media="screen" alternate="no" href="../en/error.xsl" ?>
<?xml-stylesheet type="text/xsl" href="../en/error.xsl"?>

<page>
</page>
'

!!! HUBIC fails to get oauthid
Failed to authenticate.
`

hi,

i don't know how use hubicfuse, no doc on your wiki...
and in the first, the pass under à txt config file is no very sercure...

please explain me how can use it, and may be write a basic doc...

regards,
Orka.

**Comment by TurboGit** [comment]
Have you looked at the README? Do you have created your refresh_token on OVH HubiC? Have you set your .hubicfuse config?

**Comment by olear** [comment]
Got the similar issue.
```shell
debug_level = 0
get_extended_metadata = 0
curl_progress_state = 0
enable_chmod = 0
enable_chown = 0
==DBG 0 [2016-09-01 12:53:51.]:28308==Authenticating... (client_id = 'XXXXXXXXXXXXXXXXXXX')
==DBG 0 [2016-09-01 12:53:52.]:28308==HUBIC TOKEN_URL result: '{"expires_in":21600,"access_token":"XXXXXXXXXXXXXXXXXXXX","token_type":"Bearer"}'

==DBG 0 [2016-09-01 12:53:52.]:28308==HUBIC Access token: XXXXXXXXXXXXXXXXXXXX

==DBG 0 [2016-09-01 12:53:52.]:28308==HUBIC Token type  : Bearer

==DBG 0 [2016-09-01 12:53:52.]:28308==HUBIC Expire in   : 21600

==DBG 0 [2016-09-01 12:53:52.]:28308==CRED_URL result: '{
    "error":"insufficient_scope",
    "error_description":"scope is insufficient"
}
'

==DBG 0 [2016-09-01 12:53:52.]:28308==HUBIC cannot get json field 'token'

Failed to authenticate.

```
Also under 'Applications connected to your account' I only have 'read the quota, read the settings, ' access for the app used, and I can't change this.

**Comment by pvomhoff** [comment]
@olear 
I had the same issue.
My mistake was that didn't enter the char (like "r" or "w") at the scope prompts when i run the "hubic_token" script.
So the chars in the bracket will not be used as a default value when you just press enter you have to type it and then press enter.
Hope this will also fix your problem.

**Comment by TurboGit** [comment]
Closing no answer from OP.
