### ISSUE TITLE
Unable to read files

### ISSUE THREAD

**Issue by praveenkathari** [TurboGit/hubicfuse#134]
I followed all the steps to install and it worked, but while reading files /copying file i am getting the  error as  "cp: cannot open ‘files’ for reading: No such file or directory"

**Comment by TurboGit** [comment]
No sure to understand the problem. Is the Hubic properly mounted? What was the command used to mount? What does "mount | grep hubic" command returns?

**Comment by praveenkathari** [comment]
yes , its mounted properly  using "sudo hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other"

I can see the files in the default folder and 

"mount | grep hubic" ---> hubicfuse on /mnt/hubic type fuse.hubicfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)

**Comment by praveenkathari** [comment]
I can able to mkdir "test" in /mnt/hubic but i was unable to copy or create any file 

error: "cp: cannot create regular file ‘./file.txt’: Input/output error"

**Comment by dan-cristian** [comment]
I think you cannot create files directly in the root folder, you should create the file in a subfolder.

**Comment by praveenkathari** [comment]
I create a subfolder  using the mkdir command and it was reflecting in my hubic web console , and while was create/copy any file inside the subfolder  , i am getting the error .  plz help . thanks

**Comment by drmanuel** [comment]
I've the same issue, does anyone know how to solve it?
Thanks in advance.
M.

**Comment by TurboGit** [comment]
This is the most strange issue reported, I have no clue as to what is going on. I have no issue as many other users I suppose otherwise hubicfuse would be just a bad joke! Maybe a wrong mount options? What is the permissions to you mount point before mounting hubic? We will certainly need more information to figure this out...

**Comment by drmanuel** [comment]
Sorry, for not explain me better.
This is what happen on my vps now, it worked for a lot of time but now happen this:
`root@vpsxxxxxx:~# mount | grep hubic 
hubicfuse on /mnt/cloud type fuse.hubicfuse (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other)
root@vpsxxxxxx:~# mkdir /mnt/cloud/default/tvcc/test    
root@vpsxxxxxx:~# echo test >/mnt/cloud/default/tvcc/test/test.txt
-bash: /mnt/cloud/default/tvcc/test/test.txt: Input/output error
`
Can you help me to understand? 
Thx.
M.

**Comment by TurboGit** [comment]
But the options are not the one documented!

On my side I have only:

> noauto,noauto_cache,sync_read,user,allow_other

And I can mount not as root, and copy files as myself into the mounted drive.

The user_id=0 and group_id=0 means that this is mounted as root. I've never tested that.

Also my /mnt/hubic has the user set as myself and the group is "users".

So please try:

1. unmount /mnt/hubic
2. change the fstab option with the above
3. do a logged as you:

> sudo chown $(whoami):users /mnt/hubc

4. be sure to have latest hubicfuse source and recompiled with you current kernel
    (if compiled from source, not if using the one from your distrib)
5. mount hubic
6. test the copy

Please do really all this logged as you not as root. I know this works for me.

**Comment by praveenkathari** [comment]
I guess you need to create the tmp files folders , as mentioned in config, in my case it worked . 

⁣Regards,

Praveen Kathari
CT: +919866781816
www.intoweb.in​

**Comment by drmanuel** [comment]
Ok, I solved. The problem was I deleted the tmp files folders as suggested by praveenkathari. 
Thanks to everyone for the help.
M.

**Comment by TurboGit** [comment]
Closing since solved.
