### ISSUE TITLE
fuse: bad mount point `/mnt/hubic': No such file or directory

### ISSUE THREAD

**Issue by ruzzzz6312** [TurboGit/hubicfuse#136]
Hi, please kindly help, tried on 2 cents x86 and x64, both same issue, followed 100% instructions

<img width="1013" alt="screen shot 2016-12-12 at 2 33 54 pm" src="https://cloud.githubusercontent.com/assets/23564850/21115704/2cec68d0-c078-11e6-841d-7212f0e1dffc.png">

**Comment by TurboGit** [comment]
Is /mnt/hubic a directory?

I mean before running hubicfuse you probably want to do:

> $ mkdir /mnt/hubic

**Comment by ruzzzz6312** [comment]
Yep, that resolved issue, but appeared another one
fuse: failed to open /dev/fuse: Operation not permitted
/dev/fuse has chmod -R 777
Any ideas?

**Comment by ruzzzz6312** [comment]
tried to run with privilege (i guess)
sudo /home/test3/hubicfuse/hubicfuse **--device/**mnt/hubic -o noauto_cache,sync_read,allow_other

Now receiving error
fuse: missing mountpoint parameter

**Comment by TurboGit** [comment]
Is fuse package installed?

What is **--device/** above?

Also, my /dev/fuse is:

> ll /dev/fuse
> crw-rw-rw- 1 root root 10, 229 Dec 10 17:55 /dev/fuse

**Comment by ruzzzz6312** [comment]
Centos x64, 
Package fuse-2.9.2-7.el7.x86_64 already installed and latest version
[root@test ~]# hubicfuse/hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
fuse: failed to open /dev/fuse: Operation not permitted

same issue

**Comment by ruzzzz6312** [comment]
appreciate your help.

**Comment by TurboGit** [comment]
You need /dev/fuse to be on user root and group root.

If you want then to mount as your user you'll have a add yourself to the fuse group. But this is not the issue at the moment as you're root when you tried.

**Comment by TurboGit** [comment]
BTW, I'm not a Centos user, so not sure what to do at this point... Did you tried to Google the error reported?

**Comment by ruzzzz6312** [comment]
yep, unfortunately nothing helped, thank you anyway.

**Comment by TurboGit** [comment]
Nothing else to add, closing.
