### ISSUE TITLE
debian stretch: Unmet build dependencies: libjson0-dev

### ISSUE THREAD

**Issue by chymian** [TurboGit/hubicfuse#139]
hey, 
on debian stretch (the upcoming stable) there is no "libjson0-dev" any more.

```
$ LANG=C dpkg-checkbuilddeps
$ dpkg-checkbuilddeps: error: Unmet build dependencies: libjson0-dev
```

**Comment by szepeviktor** [comment]
Actually libjson0-dev already a transitional package.
https://packages.debian.org/source/jessie/json-c

In Debian there is a `control` file for each release. For stretch it is libjson-c3
https://packages.debian.org/source/stretch/json-c

**Comment by szepeviktor** [comment]
I suggest to support only Debian stable and to add these as a comment in `control`

**Comment by szepeviktor** [comment]
@chymian See https://packages.qa.debian.org/h/hubicfuse.html
