### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by szepeviktor** [TurboGit/hubicfuse#144]
@TurboGit Could you release 3.0.1?

**Comment by TurboGit** [comment]
Sure will do after merging your patches.

**Comment by TurboGit** [comment]
Now done.

**Comment by szepeviktor** [comment]
Thanks.
Adding a title and some notes looks much better: https://github.com/szepeviktor/hubicfuse/releases
You find it on the right: https://github.com/TurboGit/hubicfuse/tags
