### ISSUE TITLE
3 patches from the Debian maintainer

### ISSUE THREAD

**Issue by szepeviktor** [TurboGit/hubicfuse#145]
- bug765288.diff              
- multi-line-http-status.patch
- preserve-cppflags.patch     

https://anonscm.debian.org/cgit/collab-maint/hubicfuse.git/tree/debian/patches

@TurboGit Please consider merging these.

**Comment by TurboGit** [comment]
Sure. What about bug765288.diff fuse version? It is set to 2.6 but latest version in Debian/stable is 2.9, is that correct?

**Comment by szepeviktor** [comment]
I [couldn't find](https://github.com/libfuse/libfuse/search?utf8=%E2%9C%93&q=FUSE_USE_VERSION&type=) references to this in the FUSE lib.
Only this one:
https://github.com/libfuse/libfuse/blob/4b58635d16791013e36d761313bec5c247eec841/include/fuse_common.h#L725-L727

So I think there is no FUSE API change for every FUSE_USE_VERSION value.

**Comment by szepeviktor** [comment]
This is the reason for bug765288.diff

https://github.com/libfuse/libfuse/blob/4b58635d16791013e36d761313bec5c247eec841/include/fuse_lowlevel.h#L12-L23

**Comment by TurboGit** [comment]
Hum...

> #if !defined(FUSE_USE_VERSION) || FUSE_USE_VERSION < 30
> #  error only API version 30 or greater is supported
> #endif

But since you set FUSE_USE_VERSION to 26 it will fail given the code you quoted!

**Comment by szepeviktor** [comment]
> It is set to 2.6 but latest version in Debian/stable is 2.9, is that correct?

But it is not in Debian :)

**Comment by szepeviktor** [comment]
You may - of course - use `30`.

**Comment by TurboGit** [comment]
Ok, let's settle on 30.

**Comment by TurboGit** [comment]
All are now integrated?
