### ISSUE TITLE
Drop /debian

### ISSUE THREAD

**Issue by szepeviktor** [TurboGit/hubicfuse#146]
I think Stephen Kitt does a better job: https://anonscm.debian.org/cgit/collab-maint/hubicfuse.git/tree/debian

https://packages.qa.debian.org/h/hubicfuse.html

**Comment by TurboGit** [comment]
Do you mean that I should dop the debian directory on the repo? Sorry for the very very late response :(

**Comment by szepeviktor** [comment]
Yes.

**Comment by TurboGit** [comment]
Done. Thanks.
