### ISSUE TITLE
SVFS vs HubicFuse

### ISSUE THREAD

**Issue by ArchangeGabriel** [TurboGit/hubicfuse#147]
Hi there,

I’m new to the hubiC world, and wondering how I should set-up this to use as a filesystem target.

I’ve seen there is this project as well as https://github.com/ovh/svfs. I’m trying to determine which one is the best to use. Apparently hubicfuse is community developed, older and more discussed around the web. svfs on the other hand is developed by OVH directly, and if at first it required regenerating manually some URL every 24 hours, this seems to be a thing of the past.

So, I’m asking here toward hubicfuse devs and (former) users, should I go for this or svfs.

Thanks!

**Comment by dan-cristian** [comment]
Hi. My advice, switch to amazon cloud drive, ovh cloud performance and
support is just terribly bad.

**Comment by ArchangeGabriel** [comment]
@dan-cristian Well, I somehow expect that, but I’d like to try to use it first since I have 2×10 To included through a DSL subscription with OVH. Also, ACD does not seems to be usable as a VFS, so this would be a nogo for me.

**Comment by hbakhtiyor** [comment]
@ArchangeGabriel what's your conclusion? did you use `svfs` instead of this?

**Comment by dan-cristian** [comment]
I switched to amazon cloud drive, i get 21 MBps upload and very fast
download. i use rclone for sync. i know it is not comparable with a fuse
setup, but i use a disk buffer and is fast and reliable.

**Comment by hbakhtiyor** [comment]
@dan-cristian is it not expensive?

**Comment by dan-cristian** [comment]
55 gbp / year for unlimited storage. i have more than 10 TB uploaded.

**Comment by hbakhtiyor** [comment]
how is it differ from s3?

**Comment by dan-cristian** [comment]
not sure, did not check in detail

**Comment by trthrrth** [comment]
Amazon banned acdcli and rclone....

**Comment by ArchangeGabriel** [comment]
And now Amazon changed unlimited to 1 TB. Good luck @dan-cristian to clean your storage!

Regarding me, I still didn’t had the time to setup either fuse or svfs, but I’ll keep this ticket updated when I’ll do.

**Comment by dan-cristian** [comment]
I'm using the windows client currently for upload, not ideal indeed. Unlimited option is still enabled/available in my subscription, i use it for backup from my NAS, so no big deal if I have to change the cloud provider.

![amazon](https://user-images.githubusercontent.com/10730231/27006529-c9736c2c-4e3e-11e7-90f8-d584ef9e0463.jpg)

**Comment by ArchangeGabriel** [comment]
@dan-cristian If you haven’t read any article about this yet, I advise you one: https://techcrunch.com/2017/06/08/amazon-ends-its-unlimited-cloud-storage-plan/.

**Comment by dan-cristian** [comment]
thanks Bruno. please let me know guys if you find a cloud alternative with
good price, very fast upload speed and a sync(upload) client working on
linux.

**Comment by ArchangeGabriel** [comment]
Just for the record, I haven’t tried SVFS and do not plan to do so unless something requires me to.
