### ISSUE TITLE
Extremely slow operations

### ISSUE THREAD

**Issue by Dece** [TurboGit/hubicfuse#149]
Hi, I compiled and installed Hubicfuse from this repo on my OVH VPS. While it correctly mounts my hubic drive on /mnt/hubic and I can `cd`, `ls` and `mkdir` relatively easily through the folders, every read or write operation on files like `touch`, `rm` or `dd` takes forever before it eventually finishes.

With debug level 2 I get those errors while writing, not sure if they're meaningful or not...

```
unique: 352, opcode: STATFS (17), nodeid: 1, insize: 40, pid: 6798
statfs /
==DBG 0 [2017-05-10 22:50:02.]:5781==cfs_statfs(/)
==DBG 1 [2017-05-10 22:50:02.]:5781==exit: cloudfs_statfs (old values, cached since 0 seconds)
==DBG 0 [2017-05-10 22:50:02.]:5781==exit 0: cfs_statfs(/)
   unique: 352, success, outsize: 96
==DBG 1 [2017-05-10 22:50:26.]:5782==status: send_request_size(/slt_segments?format=xml&delimiter=/&prefix=) completed HTTP REQ:https://lb1040.hubic.ovh.net/v1/AUTH_f5d7385b3b9675fe1ee534e1ff3dba19/slt_segments?format=xml&delimiter=/&prefix= total_time=358.1 seconds
==DBG 0 [2017-05-10 22:50:26.]:5782==send_request_size: error message, size=0, [HTTP 500] (GET)(slt_segments?format=xml&delimiter=/&prefix=)
==DBG 0 [2017-05-10 22:50:26.]:5782==send_request_size: error message=[]
==DBG 0 [2017-05-10 22:50:26.]:5782==send_request_size: httpcode=500 (GET)(slt_segments?format=xml&delimiter=/&prefix=), retrying [HTTP ERR]
```

Let me know what kind of logs I could add to help you! Thank you.

**Comment by derdigge** [comment]
i can confirm that behavior.

**Comment by meroujanantonyan** [comment]
Same,  hubicfuse block bash commands.

`juil. 15 17:43:44 nfs kernel: INFO: task dd:5386 blocked for more than 120 seconds.
juil. 15 17:43:44 nfs kernel:       Not tainted 4.9.0-3-amd64 #1 Debian 4.9.30-2+deb9u2
juil. 15 17:43:44 nfs kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
juil. 15 17:43:44 nfs kernel: dd              D    0  5386   1203 0x00000006
juil. 15 17:43:44 nfs kernel:  ffff894ef9f92800 0000000000000000 ffff894ef6aee100 ffff894effc18240
juil. 15 17:43:44 nfs kernel:  ffffffffafc0e500 ffffadb640843bc8 ffffffffaf6015d3 0000000000018240
juil. 15 17:43:44 nfs kernel:  00ff894effab0400 ffff894effc18240 ffff894efb070d50 ffff894ef6aee100
juil. 15 17:43:44 nfs kernel: Call Trace:
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf6015d3>] ? __schedule+0x233/0x6d0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf601aa2>] ? schedule+0x32/0x80
juil. 15 17:43:44 nfs kernel:  [<ffffffffc06077aa>] ? request_wait_answer+0xba/0x1f0 [fuse]
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf0b8d50>] ? prepare_to_wait_event+0xf0/0xf0
juil. 15 17:43:44 nfs kernel:  [<ffffffffc0607958>] ? __fuse_request_send+0x78/0x80 [fuse]
juil. 15 17:43:44 nfs kernel:  [<ffffffffc0610ddc>] ? fuse_flush+0x13c/0x180 [fuse]
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf1fe9ea>] ? filp_close+0x2a/0x70
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf22107c>] ? put_files_struct+0x6c/0xc0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf07b267>] ? do_exit+0x2b7/0xae0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf07bb0a>] ? do_group_exit+0x3a/0xa0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf0869a7>] ? get_signal+0x297/0x640
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf025446>] ? do_signal+0x36/0x6a0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf0b8b4c>] ? finish_wait+0x3c/0x70
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf0b8d50>] ? prepare_to_wait_event+0xf0/0xf0
juil. 15 17:43:44 nfs kernel:  [<ffffffffc0610ded>] ? fuse_flush+0x14d/0x180 [fuse]
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf003251>] ? exit_to_usermode_loop+0x71/0xb0
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf003a94>] ? syscall_return_slowpath+0x54/0x60
juil. 15 17:43:44 nfs kernel:  [<ffffffffaf606308>] ? system_call_fast_compare_end+0x99/0x9b
juil. 15 17:45:44 nfs kernel: INFO: task touch:5921 blocked for more than 120 seconds.
juil. 15 17:45:44 nfs kernel:       Not tainted 4.9.0-3-amd64 #1 Debian 4.9.30-2+deb9u2
juil. 15 17:45:44 nfs kernel: "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
juil. 15 17:45:44 nfs kernel: touch           D    0  5921   5431 0x00000004
juil. 15 17:45:44 nfs kernel:  ffff894efac83800 0000000000000000 ffff894ef90ac300 ffff894effc18240
juil. 15 17:45:44 nfs kernel:  ffffffffafc0e500 ffffadb6412f7e40 ffffffffaf6015d3 ffffffffaf0b8799
juil. 15 17:45:44 nfs kernel:  00000000412f7e78 ffff894effc18240 ffff894efbfea580 ffff894ef90ac300
juil. 15 17:45:44 nfs kernel: Call Trace:
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf6015d3>] ? __schedule+0x233/0x6d0
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf0b8799>] ? __wake_up_common+0x49/0x80
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf601aa2>] ? schedule+0x32/0x80
juil. 15 17:45:44 nfs kernel:  [<ffffffffc06077aa>] ? request_wait_answer+0xba/0x1f0 [fuse]
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf0b8d50>] ? prepare_to_wait_event+0xf0/0xf0
juil. 15 17:45:44 nfs kernel:  [<ffffffffc0607958>] ? __fuse_request_send+0x78/0x80 [fuse]
juil. 15 17:45:44 nfs kernel:  [<ffffffffc0610ddc>] ? fuse_flush+0x13c/0x180 [fuse]
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf1fe9ea>] ? filp_close+0x2a/0x70
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf1fea4f>] ? SyS_close+0x1f/0x50
juil. 15 17:45:44 nfs kernel:  [<ffffffffaf60627b>] ? system_call_fast_compare_end+0xc/0x9b`

**Comment by Dece** [comment]
Closing as hubiC is ded

**Comment by TurboGit** [comment]
@Dece : Not really dead as if you had an account it is still usable. I'm still using HubiC as it is by far the less expensive for 10Tb of storage.

**Comment by Dece** [comment]
Ah mine got closed, but I think it was because it was part of my subscription to OVH as ISP...
