### ISSUE TITLE
Wont compile with libcurl4

### ISSUE THREAD

**Issue by exussum12** [TurboGit/hubicfuse#154]
On ubuntu 18 libcurl4 is default. This wont compile with libcurl4 and requires libcurl3. Any chance of an update ?

**Comment by TurboGit** [comment]
Can you be more precise? On my Debian box my hubicfuse is linked with libcurl4.

**Comment by exussum12** [comment]
Hmm on Ubuntu 18.04 this won't compile. I have to remove libcurl4 and install libcurl3.

I made the docker image due to not being able to compile.

**Comment by TurboGit** [comment]
All is ok on my side. I was able to compile on Ubuntu 18.10. As explained in the readme I have installed the following dependencies:

```
sudo apt install gcc make curl libfuse-dev pkg-config \
        libcurl4-openssl-dev libxml2-dev libssl-dev libjson-c-dev libmagic-dev
```

This has installed (sorry for the French message):

```
Sélection du paquet libcurl4-openssl-dev:amd64 précédemment désélectionné.
Préparation du dépaquetage de .../02-libcurl4-openssl-dev_7.61.0-1ubuntu2.2_amd64.deb ...
Dépaquetage de libcurl4-openssl-dev:amd64 (7.61.0-1ubuntu2.2) ...
```

So something wrong on your side. BTW, are you sure you are using the latest version?

**Comment by exussum12** [comment]
Figured it out :( Its a ppa to get the latest version on php causing an issue with libssl.

Sorry for the invalid ticket!
