### ISSUE TITLE
Issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by DDorch** [TurboGit/hubicfuse#156]
On Ubuntu 18.04, I met this issue when mounting hubic partition: 

```
sudo mount /mnt/hubic
hubicfuse: error while loading shared libraries: libjson-c.so.2: cannot open shared object file: No such file or directory
```
For solving that I manually installed package libjson-c2 which has been replaced by libjson-c3 in Ubuntu 18.04. You can download the package at this place for x64 version: http://de.archive.ubuntu.com/ubuntu/pool/main/j/json-c/libjson-c2_0.11-4ubuntu2_amd64.deb

But then I got this error message: 

```
hubicfuse: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found (required by hubicfuse)
```

I solved this one by installing libcurl3 instead of libcurl4: 

`sudo apt install libcurl3`

And then I managed to mount the partition :)

Is it possible to update dependencies of hubicfuse in order to be compatible with Ubuntu 18.04 without all this tricks?

**Comment by TurboGit** [comment]
How was hubicfuse installed? We discussed here recently the curl4 issue, and hubicfuse is set to be dependent on libcurl4 already.

**Comment by TurboGit** [comment]
See #154

**Comment by DDorch** [comment]
It's my mistake. I had a former installation on Ubuntu 16.04 and I tried to make it works after upgrading to 18.04. I should install a new version of hubicfuse. Sorry :)
