### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ycaibb** [TurboGit/hubicfuse#162]
Hi developers, in the below codes, the lock `pool_mut` could be not released before program's exit abort();. I think there is no harm to write` pthread_mutex_unlock(&pool_mut);`  before the `abort();` for better resource management and code symmetry. Thanks!

https://github.com/TurboGit/hubicfuse/blob/34a6c3e57467b5f7e9befe2171bf4292893c5a18/cloudfsapi.c#L102-L113

**Comment by TurboGit** [comment]
Indeed, should be fixed now. Thanks.
