### ISSUE TITLE
cross compilation for Thecus NAS x86 cloudfsapi.c: In function 'send_request':

### ISSUE THREAD

**Issue by nephaste** [TurboGit/hubicfuse#23]
Hi, i found some time to have a new try on cross compilation for Thecus NAS

i simply cross compiled the following dependency (without sub dependencies otherwise the makefile need to be modified to allow the include of others libs like libiconv for example or zlib )

OpenSSL 1.0.1h
LibXML2  2.9.1
Json-c 0.12
curl 7.37
Fuse 2.9.3

everything went fine 

but on make  

i686-nptl-linux-gnu-gcc -O2 -I/raid/data/module/HubicFS/sys/include -I/raid/data/module/HubicFS/sys/include/libxml2   -I/raid/data/module/HubicFS/sys/include   -D_FILE_OFFSET_BITS=64 -I/raid/data/module/HubicFS/sys/include/fuse   -I/raid/data/module/HubicFS/sys/include   -I/raid/data/module/HubicFS/sys/include/json-c   -o hubicfuse cloudfsapi.c cloudfuse.c -L/raid/data/module/HubicFS/sys/lib -lxml2   -L/raid/data/module/HubicFS/sys/lib -lcurl   -pthread -L/raid/data/module/HubicFS/sys/lib -lfuse   -L/raid/data/module/HubicFS/sys/lib -lssl -lcrypto   -L/raid/data/module/HubicFS/sys/lib -ljson-c
cloudfsapi.c: In function 'send_request':
cloudfsapi.c:136:7: warning: call to '_curl_easy_setopt_err_long' declared with attribute warning: curl_easy_setopt expects a long argument for this option

Any idea ? seems it miss a subdependency for Curl but not sure

**Comment by TurboGit** [comment]
No response in months. Closing.
