### ISSUE TITLE
utime: Function not implemented

### ISSUE THREAD

**Issue by mkools** [TurboGit/hubicfuse#24]
First of all thanks for this great piece of software! However I have one issue (which might be by design).

I was speedtesting my hubic mounted drive, however after saving a file with wget, it gives me a delay of about 60 seconds or longer after which the following message displays:

utime(100mb.bin): Function not implemented
2014-07-09 13:04:20 (105 MB/s) - “100mb.bin” saved [104857600/104857600]

Any idea what utime means and how to prevent this delay from happening?

**Comment by TurboGit** [comment]
Anyone interested by trying to implement this?

**Comment by extremeshok** [comment]
any progress on this ?

**Comment by dan-cristian** [comment]
Is there any code sample in hubicfuse for implementing a metadata write to the cloud?
SwiftExplorer is a simple to install/use tool to check containers metadata: http://www.619.io/swift-explorer

**Comment by dan-cristian** [comment]
Did some tests and I've found that running command "touch -t 200012311800 test.txt" that aims to change the mtime flag on a file will actually erase the file content on cloud. Quite dangerous.
This seems to be a fixed bug on cloudfuse, wasn't this fixed on hubicfuse as well?
https://github.com/redbo/cloudfuse/issues/62

**Comment by TurboGit** [comment]
@dan-cristian : fix for this issue just pushed. can you double check? Thanks.

**Comment by dan-cristian** [comment]
Works well now, content not erased, thanks for the fast fix.

haiot@debian:/mnt/hubic/backup$ touch -t 200012311800 test.txt
touch: setting times of ‘test.txt’: Function not implemented
haiot@debian:/mnt/hubic/backup$ ls -al test.txt
-rw-rw-rw- 1 haiot haiot 6 Nov  7 08:37 test.txt

**Comment by dan-cristian** [comment]
Just FYI
I have completed an alpha release with utimens support (change times), seems to work well so far.
It's located here: https://github.com/dan-cristian/hubicfuse/tree/utime
I need to test it before release, code still have a lot of debugging.

I plan to add chmode, chown and xattr flags like md5 hash as well. There are some shortcomings I'll explain later.

**Comment by TurboGit** [comment]
Great news!

**Comment by extremeshok** [comment]
Sounds good, interested in the shortcomings

**Comment by dan-cristian** [comment]
Have finalised the implementation for utimens support, you can get it from this branch: https://github.com/dan-cristian/hubicfuse

in terms of shortcomings, the speed is goind to be impacted as I need to do a supplemental HEAD request to get these extended file attributes. However I have implemented many speed optimisations so I think the overall speed should be better even with utimens function enabled..

**Comment by mkools** [comment]
I didn't realize this was still being worked on, thanks will test and post findings!

**Comment by dan-cristian** [comment]
Make sure you enable the utimens feature by adding this line in ~/.hubicfuse:

 

get_extended_metadata = true

 

This will retrieve the additional metadata from cloud once, when getattr function is called for a file.

 

The extended attributes will be uploaded anyhow every time you make a change to the file, even if the above flag is set to false.

 

There are additional config flags I have added in this version to help with debugging. My config looks like this. Chmod/chwon implementation is not fully completed (will not download yet the attributes from cloud):

 

client_id = api_hubic_xxxxx

client_secret = xxxxxx

refresh_token = xxxx

cache_timeout = 6000

temp_dir = /tmp/hubicfuse

 

get_extended_metadata = true

curl_verbose = false

curl_progress_state = 1

cache_statfs_timeout = 15

debug_level = 0

curl_progress_state = 1

enable_chmod = true

enable_chown = false

**Comment by rejoc** [comment]
Great news! 

I uploaded compiled and tried this new version, enabling extended metadata.

Large files now show up with their correct size and creation date but smaller ones (the ones that already showed the correct size with the previous version) give current date (the date I first did the "ls -l" to populate the cache) for the creation date.

**Comment by dan-cristian** [comment]
I think this is as expected because you did not had the extended attributes
uploaded on those existing files. in that case i set the creation date =
now. hubic only stores by default the last modify date.

**Comment by rejoc** [comment]
I'm not sure I understand... What do you mean by "hubic stores the last modify date" ? These files were pushed to hubic some days ago but I see the current (now) date.

**Comment by dan-cristian** [comment]
I see. I can implement a fix so it preserves the date you already have, by
end of this week.

**Comment by rejoc** [comment]
That would be awesome :-)

**Comment by dan-cristian** [comment]
fix implemented: https://github.com/dan-cristian/hubicfuse

**Comment by TurboGit** [comment]
Closing has now implemented.
