### ISSUE TITLE
Centos 6.5 - Json Error

### ISSUE THREAD

**Issue by max-vmcode** [TurboGit/hubicfuse#31]
Hi,
I worked with your library on Ubuntu and worked flawlessly!
As I need to access to my files with a Centos 6.5 box I found that I was't able to compile (or better configure) the plugin because a strange lack of JSON library.

I got this message:
./configure 
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for XML... yes
checking for CURL... yes
checking for FUSE... yes
checking for JSON... no
configure: error: 'Unable to find libjson.  Please make sure library and header files are installed.'

[root@devserver hubicfuse]# cat /etc/redhat-release 
CentOS release 6.5 (Final)

I have Repository EPEL and RPMFORGE and I've installed already the libjson. Here is my yum log:
# yum install gcc make fuse-devel curl-devel libxml2-devel openssl-devel json-c-devel json-c json_simple json_diff

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
- base: mirror-fr2.bbln.org
- epel: mirror.nl.leaseweb.net
- extras: mirror-fr2.bbln.org
- remi: remi.check-update.co.uk
- remi-php55: remi.check-update.co.uk
- rpmforge: mirror.nl.leaseweb.net
- updates: mirror-fr2.bbln.org
  Setting up Install Process
  Package gcc-4.4.7-11.el6.x86_64 already installed and latest version
  Package 1:make-3.81-20.el6.x86_64 already installed and latest version
  Package fuse-devel-2.8.3-4.el6.x86_64 already installed and latest version
  Package libcurl-devel-7.19.7-40.el6_6.1.x86_64 already installed and latest version
  Package libxml2-devel-2.7.6-17.el6_6.1.x86_64 already installed and latest version
  Package openssl-devel-1.0.1e-30.el6_6.4.x86_64 already installed and latest version
  Package json-c-devel-0.11-11.el6.x86_64 already installed and latest version
  Package json-c-0.11-11.el6.x86_64 already installed and latest version
  Package json_simple-1.1-2.el6.x86_64 already installed and latest version
  Package json_diff-1.3.3-1.el6.noarch already installed and latest version
  Nothing to do

Do you know how to fix this on Centos?
Thank you so much!
Max

**Comment by julienferment** [comment]
Thxxxxxxxx p2pow350, you made my day !!!!!!

Julien

**Comment by p2pow350** [comment]
Hi Julien!
I'm really very happy that I helped you in solving the compile errors for Centos 6
This means that sometimes I will do something useful in this life..LOL!

Cheers
Max
