### ISSUE TITLE
Failed to authenticate.

### ISSUE THREAD

**Issue by grekpg** [TurboGit/hubicfuse#34]
I cant login 

i get data from https://hubic.com/home/browser/developers/  
Redirect domain - http://aaa.com/ -> here i can put anythink ? 
Client ID : my_id
Client Secret : my_secret 

then i use ./hubic_token
to get token 

put this data to ~/.hubucfuse 

and 
grek@dell-3:/tmp/hf/hubicfuse$ hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other -h
Failed to authenticate.

how to find error.

**Comment by ruzzzz6312** [comment]
Thanks, helped!

**Comment by TurboGit** [comment]
Good to hear! Thanks for the feedbacks.

**Comment by kikislater** [comment]
Still working in 2019 !
