### ISSUE TITLE
Response time very, very slow

### ISSUE THREAD

**Issue by polytan02** [TurboGit/hubicfuse#41]
Hi Guys,

I'm not sure where to speak about this so I try my luck here.

I have a VPS from OVH (debian 7) and so decided to use Hubic via hubicfuse to save my /home folder (mostly webpages and small stuff, a few bog files).

Long story short, it took me 3 days (literally) to backup 4Go of data ! The transfers rsync --progress /home/mystuff to /home/hubic is fast for big files (over a few megs/sec) but the initialisation of the transfer is taking ages ! So the small files took really loooong to copy.
By the way, I had about 15,000 files to sync.

Do you think there is anything we can do about this ?

**Comment by TurboGit** [comment]
No I think that is expected. It takes time (as you found out) to initiate a copy. I'm not sure BTW that rsync is the best tool for this as in any way the time-stamp is not kept on HubiC files. It also depends on your band width. I'm coping around 2.7Gb in 7 hours with files around 40Mo.

**Comment by alandrieu** [comment]
@polytan02 can you share the rsync command arguments ? rsync use checksums, but you can comparing files based on their size with '--size-only'.

**Comment by polytan02** [comment]
Sorry but I don't remeber what were the rsync args used :(

**Comment by polytan02** [comment]
I didn't mean to close it, sorry  !

**Comment by tornade69** [comment]
Hi,
I have the same trouble about time, so i try to use rclone. Better transfert but about 6 Mbs for 100 Go, so 5 hours.

It seem the is a new option for client is ParallelUploads, may be can it be implement ? 
In french : https://forums.hubic.com/showthread.php?3996-Fonction-de-sauvegarde-bugs-et-feature-requests&highlight=values.xml

thanks

**Comment by dan-cristian** [comment]
I have the same issue and I do not think this is working as it should. I provided debug information in this issue: https://github.com/TurboGit/hubicfuse/issues/86

**Comment by dan-cristian** [comment]
I think I found a resolution to this, see my comment here: https://github.com/TurboGit/hubicfuse/issues/86

**Comment by dan-cristian** [comment]
this should also be fixed in the last release, hubicfuse now has rsync support

**Comment by TurboGit** [comment]
Let's close this PR at this stage.
