### ISSUE TITLE
fstab mount not working on Debian 7 amd64

### ISSUE THREAD

**Issue by Elficart** [TurboGit/hubicfuse#42]
Dear all,

I just installed a fresh new Debian 7 and trying to mount with hubicfuse my hubic space.

All is running fine but if I reboot the fstab line has no effect and I don't see any errors in messages or syslog.
If I mount mannually once in the system no problems.
Here the line in fstab : hubicfuse /home/hubic fuse user,noauto,sync_read,uid=33,gid=33 0 0

If you have any ideas or how to mount automatically other than fstab would be nice...
Thank you for your help
Kindly
Arthur

**Comment by Elficart** [comment]
I'll answer myself for the workaround :) 

So my workaround is to mount the partition in /etc/rc.local with : 
sudo /usr/local/bin/hubicfuse /home/hubic -o sync_read,uid=33,gid=33 

sudo is important otherwise won't read .hubicfuse in the root dir... 

I'll close the tiket but would be more elegant to find a solution through fstab of course...

Kindly
Arthur

**Comment by daghemo** [comment]
Just in the case this can help others, "noauto" prevents the system for automatically mounting the share at boot...
When using "noauto", just run "mount /home/hubic" (or whatever else) after boot. Or maybe just remove "noauto".

**Comment by TurboGit** [comment]
> sudo is important otherwise won't read .hubicfuse in the root dir...

Also sudo is not mandatory if you have changed the mount point to be owned by the user and if you add the options users in fstab mount options.
