### ISSUE TITLE
big files and small /tmp

### ISSUE THREAD

**Issue by julienlopez** [TurboGit/hubicfuse#49]
Hi
I've been using hubicfuse to store some files from a server, and it's working great most of the time, but I'm having some issues with big files. As I understand it, it fills the /tmp (only 1Gb on my little server), so I was wondering:
- Is there any particular reason writing in /tmp is needed?
- Is it a good idea to mount /tmp directly on the drive, and will it impact the performances of my machine?
- And finally, are there any restrictions on very big files (around 5Gb for example)?

Thanks in advance, and kudos for the great work :)

**Comment by flotho** [comment]
Hy @julienlopez 

Did you tried the dlo branch? Its purpose is to deal with big files. Have a look here #52 and #5

**Comment by TurboGit** [comment]
Note that dlo branch is now merged. So just try master. Will close this ticket. Please reopen if you feel it is needed.

**Comment by julienlopez** [comment]
Hi, it's me again.
I upgraded the machine I was working on so that masked the issue for a while, but I seem to still have the same problem.
I now have 8Gb RAM, so I have a default mounted /tmp of roughly 4Gb (a tad less apparently).
And I tried to upload a file a bit bigger than 4Gb and it failed the same way, /tmp gets filled to the max, whether it is with a cp or rsync (cp simply gives error messages and never stops, rsync loads the file up to  94% then seem to freeze entirely).

Any idea what is going on?
Are there any special options I should use on mounting?

I run a Fedora distro and I just compiled hubicfuse from master this morning.

Let me know if you need anything more.

**Comment by TurboGit** [comment]
Have you tried the current master branch? Latest version should not use /tmp

**Comment by TurboGit** [comment]
Do you have temp_dir  option set in your .hubicfuse? /tmp should not be used on master!

**Comment by TurboGit** [comment]
No the other way around sorry :(

Add in your .hubicfuse:

>  temp_dir=/whatever/you/want

**Comment by julienlopez** [comment]
if I can just set it to another directory, it'll be more than fine, trying it out now...

**Comment by TurboGit** [comment]
Ok, if the /tmp dir still growth, please give me the name of the file in there.Thanks.

**Comment by julienlopez** [comment]
Still seems to be the same...
I don't see anything using ls, but using I get this:
  # lsof /tmp
  COMMAND    PID USER   FD   TYPE DEVICE   SIZE/OFF  NODE NAME
  hubicfuse 1260 root    7u   REG   0,35 4043440128 21263 /tmp/tmpfhraNgt (deleted)

Let me know if you need me anything else.

**Comment by TurboGit** [comment]
Ok, I think I found (and fixed the issue). Looks like the temp_dir was not honored for creating new files. Can you check again using master branch?

**Comment by julienlopez** [comment]
seems to work, thanks you.

I'll try the complete upload tonight to be sure, but everything seems to be ok, temp_dir is now used.

**Comment by TurboGit** [comment]
Great! Closing for now.

**Comment by cballesteros1989** [comment]
Hi,
I made a git clone using master branch and copying big file the hubicfuse using temp_dir

Thanks.
