### ISSUE TITLE
Error cnx hubic_token

### ISSUE THREAD

**Issue by Playntek** [TurboGit/hubicfuse#50]
Hi,

I'm a french user of hubicfuse but I stuck on a step of the installation. I must genere refresh_token using hubic_token but I have an error message ERR_CNX = Unexpected error trying to connect to hubiC, see error code.

My connection is good I do not understand.

Thanks,

Sebastien

**Comment by TurboGit** [comment]
Moi aussi je suis français :)

Can you tell us what you've done? The exact commands launched?Is that with the latest sources from GitHub? Which OS? Version?

Merci,
Pascal.

**Comment by Playntek** [comment]
XD... J'ai tellement l'habitude de parler en anglais sur certains forums...

En faite il me faut le "refresh_token". Donc pour l'avoir je lance directement ./hubic_token et cela plante direct. En analysant le code ca plante pour la commande 
```
out="$(wget -S -q "${CURL_OPTS}" --max-redirect 0 "${URL_AUTH}" -O /dev/null 2>&1)" 
```
au step 1.

J'ai comme l'impression aussi que la variable ${CURL_OPTS} est égale à -q.

Donc cela fait wget -S -q -q... ce qui ne fonctionne pas il me semble.

Alors ma config : Debian 7 Wheezy et j'ai pris les derniéres sources.

Merci de ton aide.

Sebastien

**Comment by Playntek** [comment]
Re,

Je viens de tester sur ma distrib Linux Mint et cela fonctionne... je pense qu'il me manque une dépendance ou un truc du genre sur ma Debian... je vais voir d'ou cela peut venir...

Sebastien

**Comment by Playntek** [comment]
Bonsoir,

Testé sur ma debian 7 (sur mon serveur) - idem

J'ai remarqué aussi que le paquet libjson-c-dev n'y est pas sur ma version Oo

Merci,
Seb

**Comment by Playntek** [comment]
Bonjour,

J'ai repris l'installation depuis le début.
Pour être sûr d'avoir les paquets de dispo. j'ai mis à jour le source.list de ma distrib => [http://librox.net/spip.php?article86] (http://librox.net/spip.php?article86)

Ensuite j'ai effectué l'installation.

J'ai généré ma "refresh_token" depuis mon linux Mint (car non fonctionnelle sur ma Debian) que j'ai copié dans mon ~/.hubicfuse.

Je lance la commande :  sudo hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other

``` Failed to authenticate ```

Merci

Sebastien

**Comment by TurboGit** [comment]
Salut,

Donc si je comprends bien tu as une machine (Linux Mint) sur laquelle tout marche ok. Tu prends les ~/.hubicfuse de cette machine sur une autre et cela ne fonctionne pas?

Je suis sur Debian sid et tout fonctionne pour moi.

Tout cela ressemble à une version d'un paquet non fonctionnel.

Chez moi:

fuse:
  Installed: 2.9.3-15+b1

libjson0:
  Installed: 0.11-4

**Comment by shellux** [comment]
Salut,

J'ai exactement le même probleme, ni hubic_token, ni le mount ne marche, je suis sur Debian 7.5 chez Kimsufi

**Comment by TurboGit** [comment]
Je ne comprends pas trop. Vos client_id et client_secret sont bien référencés sur HubiC?

**Comment by TurboGit** [comment]
Que dit hubicfuse en debug:

$ hubicfuse -d <mon-point-de-montage>

?

Il ne rendra pas la main car le mode debug force l'application en foreground, mais il est possible dans une autre console de vérifier si il est possible d'accéder au point de montage.

Aussi, comme demandé plus haut, quelles sont vos versions de fuse et json?

**Comment by shellux** [comment]
Merci pour le support rapide.
hubicfuse -d me renvoi :
!!! Authenticating... (client_id = 'api_hubic_oGCsrh0qB.........')
!!! HUBIC TOKEN_URL result: '{"error_description":"invalid refresh token","error":"invalid_request"}'

!!! HUBIC cannot get json field 'access_token'

Failed to authenticate.

Pour les version: 
Fuse: Version: 2.9.0-2+deb7u1
Libjson0: Version: 0.10-1.2


Mon fichier .hubicfuse:

client_id=api_hubic_oGCs..............
client_secret=..........
refresh_token=F5........

avec les infos récupéré depuis le site de hubic dans les details de l'application creer, et le Token refresh recuperé via le site https://api.hubic.com

**Comment by TurboGit** [comment]
Bon et bien c'est vraiment étrange, l'échec arrive très tôt!

Moi j'ai:

> !!! Authenticating... (client_id = 'api_hubic_...')
> !!! HUBIC TOKEN_URL result: '{"expires_in":21600,"access_token":"...","token_type":"Bearer"}'

Le "result" juste au dessus est le retour de la première requête avec CURL. Les trois informations passées sont celles du .hubicfuse, l'une d'elle doit être fausse. Car à ce stade le parsing json n'a pas commencé.

Peut-être un problème avec la génération des informations depuis le service HubiC? Moi j'ai utilisé le script hubic_token du dépôt.

As-tu essayé le script?

**Comment by shellux** [comment]
Oui le script hubic_token me renvoie 
Erreur inattendue en essayant de se connecter à hubiC, voir code d'error.

**Comment by TurboGit** [comment]
Quelle est la sortie de:

$ wget -S --max-redirect 0 https://api.hubic.com/oauth

**Comment by shellux** [comment]
Ca me revnoie ca:

wget -S --max-redirect 0 https://api.hubic.com/oauth
--2015-03-11 20:20:14--  https://api.hubic.com/oauth
Résolution de api.hubic.com (api.hubic.com)... 5.135.99.106
Connexion vers api.hubic.com (api.hubic.com)|5.135.99.106|:443...connecté.
GnuTLS: A TLS fatal alert has been received.
Incapable d'établir une connexion SSL.

**Comment by TurboGit** [comment]
Ok, un bug de wget qui ne support pas HTTPS :( J'ai effectivement reproduit cela localement et trouvé des forums parlant de cette erreur. La bonne nouvelle est que si tu installes curl alors wget ne sera pas utilisé.

Peux-tu vérifier que curl est installé et essayer à nouveau?

**Comment by shellux** [comment]
Avec curl ça passe sans problème.

Merci beaucoup pour ton aide et surtout pour ton projet!

Si ça peu t'aider, j'ai tester une fois le problème de curl d'utiliser le token donner par le site https://api.hubic.com (en le régénérant completement) et ça ne passe pas, seul le token récupéré avec ton script passe.

En tout cas merci encore!

**Comment by TurboGit** [comment]
Super de voir que le problème est résolu. Je vais ajouter curl dans les pré-requis!

**Comment by Playntek** [comment]
Salut, 

arrf je suis désolé j'arrive aprés la bataille... XD

Merci à vous 2 et merci Pascal pour ton projet et pour ton aide.
Je vais de suite tester cela.
Je vous fais un retour de mon coté.

Seb

**Comment by Playntek** [comment]
Bon alors moi j'ai un probléme... mais je pense que c'est pas bien grave.

```
!!! CRED_URL result: '{
    "error":"insufficient_scope",
    "error_description":"scope is insufficient"
}
'

!!! HUBIC cannot get json field 'token'

Failed to authenticate.
```

C'est pas lié aux questionx usage.r, account.r, mail d'activation...?

Seb

**Comment by TurboGit** [comment]
Oui, tu dois rentrer les valeurs entre parenthèse (ou d'autres mais pas yes) car il n'y a pas de valeur par défaut.

**Comment by Playntek** [comment]
PARFAIT ... encore un grand merci. 
En effet avec les bonnes valeurs et ton script ca fonctionne à merveille.

Ca mérite un petit article sur mon blog (au passage) [#pnt](playntek.fr).

Merci,

Sebastien.

**Comment by TurboGit** [comment]
Bon et bien bonne nouvelle alors. Je ferme ce ticket.
