### ISSUE TITLE
fusermount -u :failed to unmount

### ISSUE THREAD

**Issue by shellux** [TurboGit/hubicfuse#51]
Bonjour,

Je viens de remarquer un petit probleme que je rencontre.
Quand je lance un  
fusermount -u /mnt/hubic

 j'ai un beau
fusermount: failed to unmount /mnt/hubic: Invalid argument

Merci.

**Comment by TurboGit** [comment]
Hum étrange, tout marche bien chez moi.

> $ mount /mnt/hubic/

> $ ll /mnt/hubic/
> total 0
> drwxr-xr-x 2 obry obry 0 Mar 14 10:15 default
> drwxr-xr-x 2 obry obry 0 Mar 14 10:15 default_segments

> $ fusermount --help
> fusermount: [options] mountpoint
> Options:
> -h		    print help
> -V		    print version
> -o opt[,opt...]   mount options
> -u		    unmount
> -q		    quiet
> -z		    lazy unmount

> $ fusermount -u /mnt/hubic 

> $ ll /mnt/hubic/
> total 0


Question, as-tu monté /mnt/hubic en mode utilisateur? Sinon tu devras probablement utiliser sudo pour le unmount?

**Comment by shellux** [comment]
Salut,

Voila ce que me donne les commandes en root:

$ ll /mnt/hubic/
total 12
drwxr-xr-x 3 root root 4096 mars  12 06:25 .
drwxr-xr-x 3 root root 4096 mars  11 16:03 ..
drwx------ 3 root root 4096 mars  12 06:25 default


$ fusermount --help
fusermount: [options] mountpoint
Options:
 -h                 print help
 -V                 print version
 -o opt[,opt...]   mount options
 -u                 unmount
 -q                 quiet
 -z                 lazy unmount

$ fusermount -u /mnt/hubic
fusermount: failed to unmount /mnt/hubic: Invalid argument

**Comment by TurboGit** [comment]
Bon et bien je ne comprends pas ce qui se passe!!!

**Comment by shellux** [comment]
Bon apres avoir remonter complement le serveur je n'ai plus ce probleme...

Tu peux fermer cette issue.

**Comment by TurboGit** [comment]
Ok, fait! Merci pour le retour.
