### ISSUE TITLE
[Dlo]Feedback

### ISSUE THREAD

**Issue by flotho** [TurboGit/hubicfuse#52]
Hy,

After many months, I'm happy to have a great bandwith so that it worths to work with hubic. I firstly tried the offical hubic app for linux and it works great.
So now, I tried to transfer big files (cf #5 ) because I would like to use hubic to backup datas.
So here is my conf :
- latest stable debian
- latest dlo branch directly from git
- Compile and install successful
- I have a 3G space for temp

I tested 3 files, 1Gb and 5Gb and 10 Gb.
I used the command ```rsync -vPW --inplace /storage/XXGB.file /hubic/default```

Once each file have been scanned by rsync and hubicfuse, the logs are this :
```
* additional stuff not fine transfer.c:1037: 0 0
```
In the same time, while everything seems to be trasfer correctly (jsut a little bit slowlier as hubic official actually) I observed that the tempfs was not used but my root sseems to be used at 100% :
```
df
Filesystem               1K-blocks      Used  Available Use% Mounted on
udev                         10240         0      10240   0% /dev
tmpfs                      3293448       408    3293040   1% /run
/dev/mapper/pve-root      99083868  96855656          0 100% 
```
Once hubicfuse has been unmount, the ratio usage of root has really decreased.
So maybe we still have an issue here

I can provide additionnal tests if you lead me

**Comment by TurboGit** [comment]
This is nice report. Did you rebase dlo branch on master and fix the conflicts? If so it is maybe time to do so for me to merge. I'm not transferring big files, so I cannot test on my side.

BTW, do you have the same error in the log when using simple "cp"?

**Comment by flotho** [comment]
Hy,

I'm not a git expert so to the question of rebasing dlo branch and fixing confilcts I can say no.
I'll try with cp immediately and let you know.
regards

**Comment by flotho** [comment]
So,

I made an additionnal test with pv instead of cp so that I can see the progress.
It seems far far faster than rsync. Unfortunately, after 70% I have a broken pipe :
```
 pv /home/10Gb > ./10Gb
pv: write failed: Operation not permitted============================>                   ] 70% ETA 0:01:1
```
So with 10Gb it seems to fail

Another message : cannot create temp file for here-document: No space left on device

So I don't think I'll be able to upload big file from now with hubicfuse. 

Any additionnal test you want me to try?

**Comment by TurboGit** [comment]
A question... How did you test the dlo branch since it seems to not be working on my side? It is still using the username/password old authentication. Is that still supported?

**Comment by flotho** [comment]
Hy,

I made a git clone, then configure, make and make install. Then use the classical commands

**Comment by TurboGit** [comment]
git clone... And did you really changed to the dlo branch? I mean just a Git clone gives you the master branch which has not support for big files. I've just rebased dlo on master, so can you try with this branch (in your current clone):

>$ git fetch
>$ git branch next origin/next
>$ git checkout next
>$ ./configure
>$ make
>$ sudo make install

Waiting for your feedbacks as I'd like to merge this branch soon as it is a nightmare to maintain!
Thanks.

**Comment by flotho** [comment]
I'was  already in the dlo branch :
```
hubifuse-git# git reflog
568a8f6 HEAD@{0}: checkout: moving from master to dlo
4e1bda3 HEAD@{1}: clone: from https://github.com/TurboGit/hubicfuse.git
```
I try your proposal and send a new 10Gb transfer 

Here are some results :
```
hubicfuse -V
FUSE library version: 2.9.2
fusermount version: 2.9.2
using FUSE kernel interface version 7.19
```

I ran the following command :
``` 
hubicfuse -d /mnt/hubicfuse/ -o noauto_cache,sync_read,allow_other,no_splice_write,no_splice_move
 ```
an use the pv to transfer the 10Gb file

I observe those messages :
```
!!! entry count: 1
* About to connect() to lb1040.hubic.ovh.net port 443 (#0)
*   Trying 37.59.76.98...
* connected
* Connected to lb1040.hubic.ovh.net (37.59.76.98) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1040.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> DELETE /v1/AUTH_blabla/default_segments/10Gb/1426417499.646312/7615053824/1073741824/00000000 HTTP/1.1
User-Agent: CloudFuse
Host: lb1040.hubic.ovh.net
Accept: */*
X-Auth-Token: blabla

* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 404 Not Found
!!! Dispatching response headers
< Content-Length: 70
!!! Dispatching response headers
< Content-Type: text/html; charset=UTF-8
!!! Dispatching response headers
< X-Trans-Id: blabla
!!! Dispatching response headers
< Date: Mon, 16 Mar 2015 14:09:07 GMT
!!! Dispatching response headers
< Connection: close
!!! Dispatching response headers
!!! Dispatching response headers
< 
* Closing connection #0
```
pv has been closed afeter a few minutes and a file named 10Gb appears on the web UI
I tried with copy and rsync and it looks like the file is declared very fast in the web UI.
From now I wait for the process to end to chek how long it takes to transfer everything

Hope it helps,

regards

**Comment by flotho** [comment]
Well, it looks a little slow but the transfer seems to continue and the usage of the disk still really normal!!
Great improvements obviously

**Comment by TurboGit** [comment]
Crossing fingers :)

**Comment by flotho** [comment]
yop, after 6 hours, none of the file have been tranfered correctly.
They still in the list but with 0 bytes in the web UI.
What test can I do for you?

**Comment by flotho** [comment]
do I need to consider the message as a bug?
```
* additional stuff not fine transfer.c:1037: 0 0
```

**Comment by flotho** [comment]
well,

Restarted tests :
1Gb transfered in less than 6 minutes
5Gb transfered in less than 30 minutes

with the 10Gb the behaviour is definitively different. It looks like the segment are not analyzed and hubicfuse opening and closing connection.

Is there any segment size or timeout to set up for optimizing the transfer

**Comment by TurboGit** [comment]
The 1Gb and 5Gb files are uploaded fine?

Not sure for the 10Gb, maybe an HubiC limitation? I've never transfer such big files... Maybe the HubiC web-site has information about this?

There is a segment_size option that you can place in .hubicfuse. The current value is 1073741824. There is also a segment_above option (not sure what it is supposed to do!) with default value to 2147483648.

**Comment by TurboGit** [comment]
I just found this in the term-of-usage:

>OVH cannot guarantee that files exceeding 5 GB will
>be deposited. In the event of needing to put a file of this size online,
>OVH asks the Customer to contact the technical support team in order to find out the most
> effective method of carrying out this operation. 

Full document here: https://hubic.com/en/contracts/Contrat_hubiC_2014.pdf

**Comment by flotho** [comment]
great, we definitively found an answer!

You can merge then!

**Comment by TurboGit** [comment]
Merged!

Thanks a lot for the testing.

**Comment by flotho** [comment]
Additionnaly I tried to upload 10Gb with the official release and it succeed.
So when I'll have a little time, I'll try some parameters with segment size

**Comment by maki-chan** [comment]
segment_above is the parameter which determines at which size the file gets splitted into segments whereas segment_size determines the size of the segments. Both are in bytes.

**Comment by flotho** [comment]
Hy @maki-chan , any recommendations for those options?
My transfers are failing for hughe files
