### ISSUE TITLE
Error uploading files 

### ISSUE THREAD

**Issue by caleb85** [TurboGit/hubicfuse#53]
Hubicfuse has been working good until recently
I now get two errors whenever I try to upload a large file over 4 gb. 
I get the error "Error splicing file: Operation not permitted" and the file is not in my hubic account. 
I also get the error "Error closing file: no such file or directory" and the file is not in my hubic account
I am using ubuntu 14.04 and the latest hubicfuse on a OVH vps.

**Comment by TurboGit** [comment]
What do you mean by the latest version? From Git? Which version? What is the output for:

> $ git rev-list -1 HEAD

**Comment by caleb85** [comment]
Latest version from Git
6ab9d470fe2aa6bb9e28a9024a8fdd6be9601af9

**Comment by TurboGit** [comment]
Ok, so use the version from the tag "before-dlo". Would be nice if you could debug this a bit. I can't with my connection upload such large files, so cannot debug.

This is really a *request for HELP* from the community. Please team up to look at this issue! If this cannot be fixed I'll probably have to revert to previous version.

Thanks.

**Comment by maki-chan** [comment]
I have no problems using Debian 7.8 64-Bit on a Canadian OVH dedicated server.

Just uploaded a 6.4G file

**Comment by TurboGit** [comment]
Ok, so I'll keep this version and won't revert. Nice to have good feedbacks. Thanks.

**Comment by flotho** [comment]
@maki-chan how do you transfer big files? through rsync, cp? etc

**Comment by maki-chan** [comment]
I use cp to copy big files. If there are multiple files, I usually use the find command together with its -exec switch since this seems to be much more reliable than one cp command for all files together. So

    find . -type f -exec cp -v '{}' /mnt/hubic/default/target_folder/ ';'

seems to be more reliable than

    cp -v * /mnt/hubic/default/target_folder/

**Comment by flotho** [comment]
thanks

**Comment by TurboGit** [comment]
Closing this should be fixed now.
