### ISSUE TITLE
encfs mount on hubicfuse write file twice

### ISSUE THREAD

**Issue by svialle** [TurboGit/hubicfuse#55]
Hi,
When I mount my hubic account, with ubicfuse, everything is fine (thanks by the way :-) )
When I mount an encfs on a nfs-mount, all is fine.
But, When I mount encfs volume on a hubicfuse one, encrypted files on hubic volume are wrote twice.
It is write first, on the open/write/close (this is normal), but write a second time if I make 'ls' on the encfs volume.

It is pretty esay to reproduce:
ifconfig eth0 ; cp 1M.rand mnt_enfs/ ; ifconfig eth0 ; ls mnt_enfs/1M.rand ; ifconfig eth0
give 1MB Tx transfer for the 'cp', and another 1MB Tx for the 'ls'
Im' using the last git/master of both hubicfuse and encfs.

This is pretty bad, since it take twice the time to transfer.

I can make any test, investigations, that will help.

Thanks,
Stéphane VIALLE

**Comment by svialle** [comment]
Debug from '-d' options, mixed with operations on terminal:

initial conditions
------------------
dimanche 29 mars 2015, 16:46:41 (UTC+0200)
RX bytes:39052442 (37.2 MiB)  TX bytes:47055334 (44.8 MiB)

        unique:  opcode: LOOKUP (1) nodeid: 1 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 2 insize: 49
        unique:  opcode: LOOKUP (1) nodeid: 3 insize: 65
        unique:  opcode: OPEN (14) nodeid: 5 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 1 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 2 insize: 49
        unique:  opcode: LOOKUP (1) nodeid: 3 insize: 65
        unique:  opcode: WRITE (16) nodeid: 5 insize: 88
        unique:  opcode: SETATTR (4) nodeid: 5 insize: 128
        unique:  opcode: FSYNC (20) nodeid: 5 insize: 56
    416 unique:  opcode: WRITE (16) nodeid: 5 insize: 1104

About 448kB -> ok

        unique:  opcode: LOOKUP (1) nodeid: 1 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 2 insize: 49
        unique:  opcode: LOOKUP (1) nodeid: 3 insize: 65
    448 unique:  opcode: WRITE (16) nodeid: 5 insize: 1104

About 483kb  -> ok

        unique:  opcode: LOOKUP (1) nodeid: 1 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 2 insize: 49
        unique:  opcode: LOOKUP (1) nodeid: 3 insize: 65
    160 unique:  opcode: WRITE (16) nodeid: 5 insize: 1104

About 172kb  -> ok

      2 unique:  opcode: FLUSH (25) nodeid: 5 insize: 64

End of the cp command (1.1 MB write -> OK)
------------------------------------------
dimanche 29 mars 2015, 16:47:00 (UTC+0200)
RX bytes:40234211 (38.3 MiB)  TX bytes:48400247 (46.1 MiB)

19 seconds
Ifconfig said (46.1-44.8) 1.3MB traserred (including debug over 'ssh -C') 

start of ls command
-------------------
        unique:  opcode: RELEASE (18) nodeid: 5 insize: 64
        unique:  opcode: LOOKUP (1) nodeid: 1 insize: 48
        unique:  opcode: LOOKUP (1) nodeid: 2 insize: 49
        unique:  opcode: LOOKUP (1) nodeid: 3 insize: 65

end of ls command
-----------------
dimanche 29 mars 2015, 16:47:12 (UTC+0200)
RX bytes:40279046 (38.4 MiB)  TX bytes:49548260 (47.2 MiB)

12 seconds 1.1 MB more sent (including debug over 'ssh -C')

HERE BAD STUFF IS THAT LS TOOK 12 SECS AND SENT 1MB

**Comment by svialle** [comment]
Detailed debug output of 'ls' command following the 'cp'
dimanche 29 mars 2015, 16:47:00 (UTC+0200)


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
* Closing connection #0
!!! entry count: 3


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* Closing connection #0
!!! entry count: 3


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
!!! entry count: 1


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* Closing connection #0
!!! entry count: 1


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
..
* additional stuff not fine transfer.c:1037: 0 0
* Closing connection #0
!!! entry count: 1


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* Closing connection #0
!!! entry count: 1


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
* Closing connection #0


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
* Closing connection #0


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
* HTTP 1.1 or later with persistent connection, pipelining supported
* Closing connection #0


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* additional stuff not fine transfer.c:1037: 0 0
* We are completely uploaded and fine
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
* Closing connection #0


!!! adding header: x-object-manifest: default/encfs_v2_segments/SuEyx7R2OLrtaU8lPDk,pw0J/1427640422.765734/1048584/1073741824/
!!! adding header: x-object-meta-mtime: 1427640422.765734
!!! adding header: Content-Length: 0


* Connected to lb1.hubic.ovh.net (37.59.76.97) port 443 (#0)
...
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
!!! Dispatching response headers
* Closing connection #0


   unique: 3147, success, outsize: 16
unique: 3148, opcode: RELEASE (18), nodeid: 5, insize: 64, pid: 0
release[28605640] flags: 0x20002
   unique: 3148, success, outsize: 16
unique: 3149, opcode: LOOKUP (1), nodeid: 1, insize: 48, pid: 11696
LOOKUP /default
getattr /default
   NODEID: 2
   unique: 3149, success, outsize: 144
unique: 3150, opcode: LOOKUP (1), nodeid: 2, insize: 49, pid: 11696
LOOKUP /default/encfs_v2
getattr /default/encfs_v2
   NODEID: 3
   unique: 3150, success, outsize: 144
unique: 3151, opcode: LOOKUP (1), nodeid: 3, insize: 65, pid: 11696
LOOKUP /default/encfs_v2/SuEyx7R2OLrtaU8lPDk,pw0J
getattr /default/encfs_v2/SuEyx7R2OLrtaU8lPDk,pw0J
   NODEID: 5
   unique: 3151, success, outsize: 144

# MY LOG
----------------
mnt_encfs/1M.rand
dimanche 29 mars 2015, 16:47:12 (UTC+0200)
RX bytes:40279046 (38.4 MiB)  TX bytes:49548260 (47.2 MiB)

**Comment by romanrm** [comment]
EncFS updates something in the file after it is closed. With hubicfuse this causes the second upload. You can't use EncFS on top of hubicfuse, instead set up EncFS in the reverse mode and then rsync from that.

**Comment by svialle** [comment]
Thanks, I cannot use reverse mode, since I have to rsync source files/dirs based on directory pattern.
The goal of the operation:
my rasperry, 
  - mount my NAS shares (ro)
  - mount hubic
  - rsync some directories (not all), fro may NAS, based on their names pattern match, to hubic, with crypto.
  - umount everything, awaiting next sync slot.

Any other idea ?
thanks

**Comment by romanrm** [comment]
@svialle one way (how I do it) is to separate the data you need to upload, and the data you don't, into two separate dirs: /mnt/share/ForHubic, /mnt/share/LocalOnly; then logically merge those using some sort of UnionFS-like project (such as mhddfs) for convenience in actual use.

**Comment by romanrm** [comment]
@svialle one way (how I do it) is to separate the data you need to upload, and the data you don't, into two separate dirs: /mnt/share/ForHubic, /mnt/share/LocalOnly; then logically merge those using some sort of UnionFS-like project (such as mhddfs) for convenience in actual use.

**Comment by svialle** [comment]
Year ... nice operation.
I do not want to split my backup, and I think, I will prefer the two writes, "just" leading to twice the transfer time :-)
Bus since, both, encfs, and hubicfuse works fine, each, I guess it should be a way to make them works fine together :-)
cheers

**Comment by TurboGit** [comment]
Not sure what could be done here. I'm not using EncFS, so closing now. Please reopen if someone contribute a patch. I'm really open to whatever contribution but again I don't have the time to implement everything.
