### ISSUE TITLE
Images are not processed as such

### ISSUE THREAD

**Issue by chauffer** [TurboGit/hubicfuse#56]
Steps:
Upload a picture through hubicfuse
Upload a picture through the web client

Expected behaviour:
Both pictures are downloadable and able to be seen (gallery) on the web client

Actual result:
Only the picture uploaded through the web client is able to be seen (gallery) on the web client

I don't know if the API exposes anything regarding that, but it'd be certainly a great feature to add.

**Comment by TurboGit** [comment]
I suppose the Web Client is doing something special indeed. Hubicfuse is a mount point to transfer files seen as chunk of bytes. This is not the right level to mess with whatever mime type. Frankly if someone comes with a patch I can reconsider and try to merge but I do not have the motivation nor the time to work on this.
