### ISSUE TITLE
Not functioning anymore on CentOS

### ISSUE THREAD

**Issue by zebu1er** [TurboGit/hubicfuse#58]
The .configure script requests json-c version >= 0.20 while provided is 0.11 !
This definitely prevents from compiling.

**Comment by TurboGit** [comment]
0.11 is quite old no? 

Have you tried running autoconf && ./configure ?

I do not see any hard coded value of 0.20 in the configure.ac.

**Comment by zebu1er** [comment]
The configure script failed after line 3600, but after autoconf it fails earlier :
./configure: line 2901: PKG_PROG_PKG_CONFIG: command not found
./configure: line 2904: syntax error near unexpected token `XML,'
./configure: line 2904: `PKG_CHECK_MODULES(XML, libxml-2.0, , { { $as_echo "$as_me:$LINENO: error: 'Unable to find libxml2. Please make sure library and header files are installed.'" >&5'

I cannot figure what line 2901 means !

**Comment by zebu1er** [comment]
NB : pkgconfig RPM package is already installed !

**Comment by TurboGit** [comment]
You also seem to have an old pkgconfig. Let's wait for some CentOS people to comment on this. I'm using GNU/Debian so cannot really help.

**Comment by zebu1er** [comment]
No idea if what required version, I'm having :
pkgconfig-0.23-9.1.el6.x86_64

**Comment by TurboGit** [comment]
I have 0.28. But this is also maybe an autoconf version issue, I'm using 2.69.

Which CentOS version are you using?

**Comment by zebu1er** [comment]
I'm using CentOS 6.6 x64, my autoconf if of version 2.63.

**Comment by zebu1er** [comment]
It worked ! In fact it just needs an environment variable and another package to be installed :
yum install file-devel
PKG_CONFIG_PATH=/lib64/pkgconfig ./configure

**Comment by zebu1er** [comment]
Thanks TurboGit !

PS : The readme may be updated !

**Comment by TurboGit** [comment]
Good to hear! README updated. Thanks.
