### ISSUE TITLE
hubic_token script and spaces in the password

### ISSUE THREAD

**Issue by szepeviktor** [TurboGit/hubicfuse#60]
hubic_token doesn't handle spaces in the main hubiC password.
After changing my password it works.

**Comment by TurboGit** [comment]
A known issue yes. Would be nice to fix at some point. Any patch?

**Comment by szepeviktor** [comment]
https://github.com/TurboGit/hubicfuse/pull/61

**Comment by TurboGit** [comment]
Thanks. Merged.
