### ISSUE TITLE
fuse: invalid argument `fuse'

### ISSUE THREAD

**Issue by fcjurado** [TurboGit/hubicfuse#62]
I get this error after executing the "hubicfuse /mnt/hubic fuse user,noauto 0 0". The previous commands worked as expected.

I'm running it on an ElementaryOS Luna (Linux 3.2.0-80-generic #116-Ubuntu SMP Mon Mar 23 17:11:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux)

**Comment by TurboGit** [comment]
No sure to understand. The text "hubicfuse /mnt/hubic fuse user,noauto 0 0" is not a command but the entry for the /etc/fstab file. Is that the confusion here?

**Comment by fcjurado** [comment]
Sorry, my mistake. I did't read the line above. Please close the issue

**Comment by TurboGit** [comment]
Closed.
