### ISSUE TITLE
Trying to use hubicfuse with Plex

### ISSUE THREAD

**Issue by SBerda** [TurboGit/hubicfuse#63]
Hello,
This is not an issue regarding the software but more a general question, I do have a small VPS Online running on a ubuntu server with hubicfuse and plex media server , a trial 25go hubic account, I have uploaded a video of 400mb (mkv file) on the hubic account.
I after all the setup, I'm able to find the hubic folder on plex and use it as directory for my files but when I try to read it, it doesn't work..
Do anybody have an idea how to fix this? This software would be fantastic with plex.
Thank you
Best regards :)

**Comment by TurboGit** [comment]
It doesn't work? What do you mean? Was the upload done fine? Do you see the mkv file from the Web interface?

**Comment by seppi91** [comment]
I think this issue is correlated with #65. I also tried to make hubicfuse working with my streamingserver. Unfortunately it's downloading the entire file (as described in #65), which makes it impossible to read metadata or start a stream in an appropriate time.

@TurboGit Maybe you could make it to us more clear why it's not possible to stream files. In my understanding it should be possible to read the first bytes of a filestream as soon they are downloaded, but I'm no specialist of fuse or swift protocol ;-)

**Comment by GithubicFR** [comment]
Hello,
I have same project (Plex server on a VPS+ hubic storage attached with hubicfuse).
If it could help, i use an application on my android phone ("Hubic Sync and Stream") and movies open instantly. From a user point of view, it seems possible to stream big file with hubic :)
I use subsonic on my vps and thanks to hubicfuse i could stream my music, it's really awesome!
If i could do the same with movies, i will have the ultimate cloud based mediacenter solution !

**Comment by SBerda** [comment]
I didn't thought about the music, but yes if only we could download a part of a file and after get the other parts it would be awesome!

**Comment by bpolaszek** [comment]
Hi there, 
Happy to see I'm not the only one trying to make Plex Work with hubiC storage :)
I also have a dedicated server running ubuntu trusty64. I mounted hubiC with hubicfuse and tried to put some mkv files on it. Here's what happens: 
- From my Filezilla client (windows), when I connect to my server via ssh and upload files directly in the hubic mouting point (let's say, /mnt/hubic/default/Videos), videos are 0 bytes at the end, though no error occured during upload. .srt files are ok.
- When I upload my video files to a local folder on my server, then move these files to the hubiC folder, everything works fine, the mkv files aren't 0 bytes anymore.
- When I add /mnt/hubic/default/Videos to Plex, it takes an eternity to index it (despite my server is hosted by OVH and down/up rates are very satisfying between the two), but at the end, I can see all my Videos on the Plex homepage, with grabbed metadata.
- However, when I try to play a video on Plex that is hosted in the hubiC folder, it tries to load for around 1 minute, but fails.

**Comment by Nerwysh** [comment]
HI !

Same issue :( any solutions ?

**Comment by SBerda** [comment]
Hello,
I ended up using http://www.tinymediamanager.org/ to manage my files, less sexy and less features but it works.

Hope somebody will find a solution.

Best regards

**Comment by Nerwysh** [comment]
Thx, I will try your alternative :)

**Comment by seppi91** [comment]
You should also give s3ql in combination with hubic2swiftgate a chance. It works really great and I'm not faceing any issues at the moment.

**Comment by CharlieHD** [comment]
seppi91, you got this working with s3ql in combination with hubic2swiftgate?

**Comment by seppi91** [comment]
@CharlieHD: Yep.

**Comment by CharlieHD** [comment]
Hey seppi91, thanks for your reply.

There is so little documentation on the s3ql and hubic2swiftgate combo, is it hard to set up? I was barely able to setup HubicFuse, so not sure if I could.

I don't suppose I could ask/pay you for a guide on installing it?

**Comment by SBerda** [comment]
Hello, Like Charlie I would be really interested in a small guide :)

**Comment by seppi91** [comment]
I did a small write up on my blog http://blog.se-mi.de/howto-setup-s3ql-to-use-hubic-as-storage-provider/. I haven't tested it really properly and most of the content is written out of my mind so don't expect a perfect tutorial. If you like to give me a small donation for my work, there is a button for this. I would be glad if you do so.

Further comments to s3ql and how to setup should be posted on my blog or anywhere else. This is no discussion forum and I think TurboGit isn't really happy about this off-topic talk ;)

**Comment by oskarszoon** [comment]
@seppi91 Your blog has gone offline, any chance you could post the s3ql hubic tutorial steps somewhere else?

**Comment by seppi91** [comment]
@oskarszoon I'm sorry for this. Unfortunately I didn't made a backup of my writeup. But I wouldn't bother too much about hubic anymore, as amazon cloud drive is the far more superior offer on the market. For this service there's a writeup on https://amc.ovh/

**Comment by dan-cristian** [comment]
Not sure if the comparison table is correct:

 


Provider

FUSE filesystem

Throughput (network)*

Storage

Price (USD)


hubiC

✓ Yes (unstable)

✗ 10 Mbps capped

10 TB**

$5.56

 

I get 25 Mbps (3 MB/s) upload rate on hubic, probably can  go faster but this is my ISP limit.

 

Current FUSE implementation (hubicfuse) is indeed unstable but hopefully with all recent improvements pending a merge will be much close to STABLE status.

**Comment by seppi91** [comment]
Well maybe it's outdated and hubic increased their bandwidth limit. From my own experienee there was an bandwidth limit active some months ago. At ACD I can fully saturate my gbit (duplex) link which is quite remarkable.

**Comment by dan-cristian** [comment]
There is indeed a limit with OVH, that is per connection, I see that I get max ~1000 Kbps for each upload connection. The hubicfuse implementation is using multiple upload threads for large files and this way you can get a higher upload throughput. But I agree, for smaller files it will appear slow, so ACD scores better here.

**Comment by TurboGit** [comment]
Let's close this for now, nothing to add.
