### ISSUE TITLE
"Stream" file content

### ISSUE THREAD

**Issue by swmarc** [TurboGit/hubicfuse#65]
I understand that hubicfuse is downloading the whole file in a temporary manner and also the official statement of hubic is, that there's no support for streaming. I wonder if the last point just means that there's no implementation in there web interface for multimedia stuff.
The reason for my question is that I've tried expandrive which unfortunately is just available for Windows and Mac OS.

If I add hubic in expandrive and open a rather large file (multiple 100 megabytes up to more than 1 gigabyte) it mostly opens instantly if I omit certain latencies, means it just takes a couple of seconds.

I wonder if it is may possible for hubicfuse to not download the whole file before opening or is fuse the limiting factor?

**Comment by TurboGit** [comment]
As far as I understand this is the way HubiC works and there is no (easy) way around.
