### ISSUE TITLE
Software caused connection abort

### ISSUE THREAD

**Issue by dokapp** [TurboGit/hubicfuse#66]
hi,

whenever i try to tansfer a file i get: Software caused connection abort after it finishes and the mountpoint is broken.

please advise.

**Comment by dokapp** [comment]
update: its working now, but i got HUGE problems after the transfer should be finsihed - rsync and cp need a long time to finish up.

after using debug mode i found that the client gets a shitton of 
< HTTP/1.1 404 Not Found

and after a while i finally get the:
< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 201 Created

**Comment by dan-cristian** [comment]
I have implemented several speed/reliability fixes in my branch (https://github.com/dan-cristian/hubicfuse), should resolve the issue you've mentioned.

**Comment by TurboGit** [comment]
Ok, closing now. Let see if there is still issue with the new version.
