### ISSUE TITLE
hubic_token has a problem with e-mails with "+" in them.

### ISSUE THREAD

**Issue by antymat** [TurboGit/hubicfuse#67]
Hi,

I use email in a form of "user+extension@server.com" to log-in to hubic, and the hubic_token script has failed to log me in when I gave the email as above. Only after putting "user%2Bextension@server.com" it worked. Maybe the user email address should also be processed by urlenc?

BR,

M.W.

Update: this happend with the git commit 9e593fcb260dbaf65b72cdf0bf74c92353ebaeea

**Comment by TurboGit** [comment]
Most probably yes.

Can you test with this patch? Or with the encode-email branch?

commit 12786e0818d83ec293fb210f9fcf6488b44a1ef9
Author: Pascal Obry <pascal@obry.net>
Date:   Sun May 3 21:08:40 2015 +0200

    Properly encode the user login.
---
 hubic_token | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/hubic_token b/hubic_token
index 88d567a..2d50a2c 100755
--- a/hubic_token
+++ b/hubic_token
@@ -496,7 +496,7 @@ out="$(
         stty echo 2>/dev/null
     fi
     printf '\n' >&2
-    POST="$( printf '%s' "${scope}" | sed 's|,|\&|g;s|\.|=|g' )&oauth=${oauth}&action=accepted&login=${user_login}&user_pwd=$(urlenc "${user_pwd}")"
+    POST="$( printf '%s' "${scope}" | sed 's|,|\&|g;s|\.|=|g' )&oauth=${oauth}&action=accepted&login=$(urlenc "${user_login}")&user_pwd=$(urlenc "${user_pwd}")"
 
     ccurl "${URL_AUTH}/auth/" "${CURL_DATA}" "${POST}"

**Comment by antymat** [comment]
Hi,

Yes, this is much better. It worked.

**Comment by TurboGit** [comment]
Thanks for the quick test. Fix pushed on master.

**Comment by antymat** [comment]
Thank you for the quick fix :).
