### ISSUE TITLE
 fuse: device not found

### ISSUE THREAD

**Issue by rcasunshare** [TurboGit/hubicfuse#69]
hello, I do everything right but when I try to mount the hubiC I get this err

root@radiocar:/# hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
fuse: device not found, try 'modprobe fuse' first

OS: Debian 7  wheezy

It is much appreciated assistance

**Comment by TurboGit** [comment]
Do you have the fuse package installed?

$ sudo apt-get install fuse

**Comment by rcasunshare** [comment]
Yes is install

root@radiocar:/home/sunshare# apt-get install fuse
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  fuse
0 upgraded, 1 newly installed, 0 to remove and 238 not upgraded.
Need to get 70.5 kB of archives.
After this operation, 193 kB of additional disk space will be used.
Get:1 http://http.us.debian.org/debian/ testing/main fuse amd64 2.9.3-15+b1 [70.                                        5 kB]
Fetched 70.5 kB in 0s (142 kB/s)
Selecting previously unselected package fuse.
(Reading database ... 80116 files and directories currently installed.)
Preparing to unpack .../fuse_2.9.3-15+b1_amd64.deb ...
Unpacking fuse (2.9.3-15+b1) ...
Processing triggers for man-db (2.7.0.2-5) ...
Setting up fuse (2.9.3-15+b1) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for initramfs-tools (0.119) ...
update-initramfs: Generating /boot/initrd.img-3.2.0-4-amd64
root@radiocar:/home/sunshare# hubicfuse /mnt/hubic -o noauto_cache,sync_read,all                                        ow_other
fuse: device not found, try 'modprobe fuse' first
root@radiocar:/home/sunshare#

**Comment by TurboGit** [comment]
So I suppose that you don't have the fuse module loaded for some reason. What is the output for:

$ lsmod  | grep fuse

If the output is empty you may try to force load it:

$ sudo insmod fuse

But I doubt this will help as fuse should be loaded automatically. Are you using a standard kernel?

An option is to upgrade to Jessie just released.

**Comment by rcasunshare** [comment]
Thanks for the help, the option of upgrade makes me impossible for now.
I will try to solve the fuse module

**Comment by TurboGit** [comment]
You closed it... Did you find the issue?
