### ISSUE TITLE
Cannot create mount point

### ISSUE THREAD

**Issue by deadbird99** [TurboGit/hubicfuse#71]
When using 
hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
I get:
fuse: device not found, try 'modprobe fuse' first
When using "modprobe fuse", i get this:
libkmod: ERROR ../libkmod/libkmod.c:578 kmod_search_moddep: could not open moddep file '/lib/modules/2.6.32-37-pve/modules.dep.bin'

Can you help?

**Comment by TurboGit** [comment]
Don't know. You should ask in a forum for your distribution. Clearly this is not a hubicfuse issue but a kernel/distrib issue.
