### ISSUE TITLE
hubic_token does not support % in user_pwd

### ISSUE THREAD

**Issue by danielbartz** [TurboGit/hubicfuse#72]
Changing my password remove the "%" character did the trick.

**Comment by TurboGit** [comment]
Probably indeed, a % should probable be rewritten as %% when sending it as URL with curl.

**Comment by alandrieu** [comment]
You need to make a function like [encodeURIComponent()](http://www.w3schools.com/jsref/jsref_encodeURIComponent.asp) to encode these characteres '/ ? : @ & = + $ #'.
