### ISSUE TITLE
Can't get refresh token from hubic_token

### ISSUE THREAD

**Issue by jgiovaresco** [TurboGit/hubicfuse#73]
Hi,

hubic_token doesn't give me a refresh token.

```
~/DEV/opensources/hubicfuse(branch:master) » ./hubic_token 
Response inattendue d'hubiC. Votre wget/curl supporte-t-il HTTPS ?
Réponse complète du serveur:
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Set-Cookie: api.hubic.com=R411990887; path=/; expires=Sun, 14-Jun-2015 02:32:07 GMT
Server: nginx/1.4.7
Date: Thu, 11 Jun 2015 14:29:16 GMT
Content-Type: text/html
Content-Length: 184
Location: http://api.hubic.com:443/oauth/
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
```
I'm on Debian Wheezy and curl is installed.

I try to add ``-L`` to curl command but unsuccessful

```
Response inattendue d'hubiC. Votre wget/curl supporte-t-il HTTPS ?
Réponse complète du serveur:
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Set-Cookie: api.hubic.com=R411991976; path=/; expires=Sun, 14-Jun-2015 02:55:40 GMT
Server: nginx/1.4.7
Date: Thu, 11 Jun 2015 14:42:36 GMT
Content-Type: text/html
Content-Length: 184
Location: http://api.hubic.com:443/oauth/
Connection: keep-alive

**[weird characters]**
```

**Comment by TurboGit** [comment]
You probably want to install libcurl3-gnutls package.

**Comment by jgiovaresco** [comment]
This package is already installed. (version 7.26.0-1+wheezy12)

**Comment by TurboGit** [comment]
The only idea I have at this point is that there is indeed a too old library somewhere. Maybe libjson? Can you upgrade to Jessie?

**Comment by jgiovaresco** [comment]
I plan to upgrade to Jessie in few weeks. I will let you know.

**Comment by jperon** [comment]
Same issue here ; I am on debian unstable.

**Comment by TurboGit** [comment]
@jperon, I'm on unstable too, last time I've been using hubic_token I was on a pre-version of Jessie.

If you have wget installed, uninstalled it to force use of curl and see if this fix the issue. Please report here your finding. Thanks.

**Comment by jperon** [comment]
After uninstalling wget (using --force-deps because of multiple packages depending on it), the error remains the same : 
```
Response inattendue d'hubiC. Votre wget/curl supporte-t-il HTTPS ?
Réponse complète du serveur:
HTTP/1.1 200 Connection established

HTTP/1.1 301 Moved Permanently
Set-Cookie: api.hubic.com=R411991976; path=/; expires=Sat, 01-Aug-2015 06:41:46 GMT
Server: nginx/1.4.7
Date: Wed, 29 Jul 2015 18:24:17 GMT
Content-Type: text/html
Content-Length: 184
Location: http://api.hubic.com:443/oauth/
Connection: keep-alive

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.4.7</center>
</body>
```

N. B. : I'm behind a proxy, so I set `http_proxy` and `https_proxy` environment variables before running `hubic_token`.

**Comment by TurboGit** [comment]
Ok, maybe a proxy issue then since hubic_token works for many people. I'm no proxy expert but maybe yours is not configured to support https? Anyway, I don't see what could be done. You may want to check that it is working fine for you from a machine without proxy.

**Comment by TurboGit** [comment]
Closing, nothing more to do I suppose.
