### ISSUE TITLE
it does not work in 15.04

### ISSUE THREAD

**Issue by edib** [TurboGit/hubicfuse#74]
I have followed the readme file then it says there is no command like hubicfuse. I have installed via apt-get install hubicfuse then it says that there must be a file in $HOME/.cloudfuse containing username, password etc. I have said ok then I have created the file then it says authentication failed but it is impossible. I think there is another command coming from this build "cloudfuse". It produce same output.

**Comment by agauthier51** [comment]
Hello, this version of hubicfuse produces a binary called hubicfuse and uses a configuration file called .hubicfuse

You should retrieve the files and build a new deb file. Everything is provided.

Regards,
Arnaud

**Comment by TurboGit** [comment]
@edib, is that fixed for you now?

**Comment by TurboGit** [comment]
Closing as no feedback.
