### ISSUE TITLE
Stuck at mounting hubic

### ISSUE THREAD

**Issue by Talos51** [TurboGit/hubicfuse#75]
Hi !

I tried to install hubicfuse on a OVH VPS ( debian 7 Wheezy x64 ) but i'm stuck at mounting it. when i run  
```
sudo hubicfuse /mnt/hubic -d -o noauto_cache,sync_read,allow_other
``` 
Here's the following display that stucks after CRED_URL part before the FUSE part ( maybe libfuse issue ? )
```
!!! Authenticating... (client_id = 'api_hubic_XxxxxX')
!!! HUBIC TOKEN_URL result: '{"expires_in":21600,"access_token":"XxxXxXX","token_type":"Bearer"}'

!!! HUBIC Access token: XxxxXxxXX

!!! HUBIC Token type  : Bearer

!!! HUBIC Expire in   : 21600

!!! CRED_URL result: '{"token":"Xxxx","endpoint":"https://lb1040.hubic.ovh.net/v1/AUTH_xxXXXx","expires":"2015-07-13T14:10:37+02:00"}'

```

And to be sure, i've run the same install procedure on a debian VM and it works on it, so that's not some problem with .hubicfuse file or my credentials.
So I'm sure that something is missing on VPS, and I wonder if there's a specific port to open cause I use IPTables and I think there's maybe a rejected connection ?

* Libjson0 Version: 0.10-1.2 // Libfuse 2 Version: 2.9.0-2+deb7u2 // Curl Version: 7.26.0-1+wheezy13
* Tried to run as root and with sudo under normal user.
* Using the latest Git version of hubicfuse
* sudo ls -al /mnt/hubic get stuck as well
* wget http / https works fine

All required packages are installed : ```gcc make curl libfuse-dev pkg-config libcurl4-openssl-dev libxml2-dev libssl-dev libjson-c-dev libmagic-dev build-essential libjson0-dev fuse-utils```

Thanks!

**Comment by TurboGit** [comment]
Is the VM running the same Debian version? IIRC hubicfuse use port 80 only.

**Comment by Talos51** [comment]
Yes the VM is running Debian 7, i've tried to keep the VM as close as my VPS to test development work and port 80 is open for my web server... So maybe libfuse problem ?

**Comment by TurboGit** [comment]
Probably a fuse kernel issue indeed, I have no better explanation anyway.
