### ISSUE TITLE
RamUsage

### ISSUE THREAD

**Issue by saschaarthur** [TurboGit/hubicfuse#77]
Hey,

Im trieing to upload huge files (~80GB backups) via hubicfuse. Im mounting my hubicfuse with:

hubicfuse /h -o noauto_cache,allow_other,direct_io,intr,max_background=1,atomic_o_trunc,big_writes,sync_read,max_readahead=100M

i tried to copy with:
scp -l 80000 $source/\* $hubic

Anyways it seems that hubicfuse is loading the WHOLE file in RAM before it starts to copy to hubic, Because my system starts swapping.. even if theres a bandwith limit?

Is this a known issue? Any sugesstions?

**Comment by TurboGit** [comment]
Not sure hubicfuse is ready for a 80GB download. Again I'm not using hubicfuse in such context, so cannot comment for sure...

Just a question, which version of hubicfuse are you using?

**Comment by saschaarthur** [comment]
hey,

Thanks for the reply! Im using the latest GIT version (master).

Im talking about uploading a 80GB file not downloading. Is there maybe a need for creating a checksum first or something like that?

**Comment by TurboGit** [comment]
Right, uploading that's what I had understood. Again I'm not sure such large file is properly supported as I'm not setup to test this. My connection is too slow!

**Comment by saschaarthur** [comment]
hey,

You can easily test it, just try to copy a file via hubic. Its instantly loaded into the ram, you dont have to wait for the full upload.

**Comment by TurboGit** [comment]
Maybe worth testing with latest version of hubicfuse. Can you do that and report back if it is working now?

**Comment by TurboGit** [comment]
No answer, closing.
