### ISSUE TITLE
CentOS: error while loading shared libraries: libjson-c.so.3

### ISSUE THREAD

**Issue by LTGIV** [TurboGit/hubicfuse#78]
HubicFuse works flawlessly on Ubuntu, but fails on CentOS.
- No json-c-devel exists for yum install, even with EPEL
- I clone json-c and configure, make, make install.

I tried configure, make, make install for hubicfuse even with changing json-c --prefix to /usr and
export JSON_CFLAGS='-I/usr/include/json-c/'
export CPPFLAGS='-I/usr/include/json-c'
export JSON_LIBS='-L/usr/lib -ljson-c'

hubicfuse successfully compiles and installs, but when executed, gives error:

hubicfuse: error while loading shared libraries: libjson-c.so.3: cannot open shared object file: No such file or directory

No matter if I put them with prefix of /usr or leave them at default /usr/local

**Comment by TurboGit** [comment]
You may try to add the path to libjson-c.so.3 in LD_LIBRARY_PATH.

**Comment by TurboGit** [comment]
Ping? Is that fixed? Should this ticket be closed?

**Comment by TurboGit** [comment]
No answer, closing.
