### ISSUE TITLE
Account parameters as arguments?

### ISSUE THREAD

**Issue by Profforgr** [TurboGit/hubicfuse#80]
Hello.

Is there an way to pass Hubic account paramters as arguments to hubicfuse command? To not use $HOME/.hubicfuse
I mean: 
        client_id=[Hubic client id for the registered application]
        client_secret=[Hubic client secret for the registered application]
        refresh_token=[A refresh token you got from the script]

I need this to use multiple hubic accounts (maybe even few accounts concurrently, did not tested this possibility). Not to abuse Hubic but to backup each website to separete account (to it's owner's account), this is for some sort of shared hosting.

**Comment by TurboGit** [comment]
Yes, sure just do:

> $ hubicfuse /mnt/hubic -o client_id=api_hubic...,client_secret=...,refresh_token=...

You may want to add other options.

**Comment by Profforgr** [comment]
Thanks! Did not thought that it's so easy -)
