### ISSUE TITLE
Failed to authenticate.

### ISSUE THREAD

**Issue by albebert** [TurboGit/hubicfuse#81]
Can't get the new version working, 

i've a old version that work.

but with new version can't auth

i use hubic_token tu generate the refresh token but doesn't work

**Comment by TurboGit** [comment]
Without more information it will be difficult to help. Many people are using current version of hubicfuse without trouble, so that's most probably a setup issue on your side.

One known issue is a % in the password which is not properly encoded and hubic_token does not generate a proper auth ids.

**Comment by albebert** [comment]
after lots of retry it's work ! don't know why nothing changed

sorry

**Comment by TurboGit** [comment]
Maybe a transient issue with the Hubic auth service? Anyway good to hear it is working. Closing.

**Comment by Kerwood** [comment]
I have the same problem.. How did you get past it ?

**Comment by Kerwood** [comment]
Never mind.. I det not write the letters in the parentheses.
