### ISSUE TITLE
Failed to authenticate ... how to debug ?

### ISSUE THREAD

**Issue by MykeulGit** [TurboGit/hubicfuse#84]
Hello,

I follow the procedure, with "application creation" in the HubiC portal, then hubic_token (with default parameter for rights), copy the content in ~/.hubicfuse, and doing everything as root.
I still have Failed to authenticate, and no way to investigate at all.

What should I do ? Is this a bug ?

Regards

**Comment by MykeulGit** [comment]
Hello,

Nevermind, I am stupid. 
Even if I spent several hours on it ... I just had to READ that in hubic_token rights "(r)" does not mean that it is automatically entered, it means it is an advice ...

Sorry for disturbing

**Comment by TurboGit** [comment]
A common mistake! Closing.
