### ISSUE TITLE
device not found, try 'modprobe fuse' first

### ISSUE THREAD

**Issue by JW94** [TurboGit/hubicfuse#85]
I tried CentOS, Ubuntu, Debian. Every system didn't work and the output is:
"device not found, try 'modprobe fuse' first".

 It seems, that fuse isn't able to run because the modules aren't loaded. 
When I try to run "modprobe fuse" this happens:

"modprobe: ERROR: ../libkmod/libkmod.c:508 kmod_lookup_alias_from_builtin_file() could not open builtin file '/lib/modules/2.6.32-042stab111.11/modules.builtin.bin'
modprobe: FATAL: Module fuse not found."

I tried to reinstall fuse and reinstall the kernel but nothing worked.

**Comment by JW94** [comment]
Ah, i got out why it didn't work. I have a virtual server and therefore it isn't possible to use fuse.

**Comment by TurboGit** [comment]
Ok, closing then. Nothing to do.
