### ISSUE TITLE
Very slow start when copying a file

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#86]
I have mounted hubicfuse in /mnt/hubic and I copy a 25 MB file. The copy is very slow, more than 2 minutes.
I enabled debug and I get 5 HTTP 404 errors before the actual copy starts.
I monitor the ethernet link and the upload speed is 3 MB/s, once the actual upload starts.
I use the latest version from github.
See below the commands I run and some debug information.

Can you advise what is the issue and how can I get the copy work faster?

root@debian:~# date
Mon Nov  2 01:53:17 EET 2015
root@debian:~# cp -v webmin_1.770_all.deb /mnt/hubic/backup/test4
‘webmin_1.770_all.deb’ -> ‘/mnt/hubic/backup/test4’
root@debian:~# date
Mon Nov  2 01:55:43 EET 2015

root@debian:~# ls -al /mnt/hubic/backup
total 156236
drwxr-xr-x 2 root root        0 Nov  2 01:59 .
drwxr-xr-x 2 root root        0 Jan  1  1970 ..
-rw-rw-rw- 1 root root   307621 Nov  1 21:57 duplicity-full.20151101T215717Z.manifest
-rw-rw-rw- 1 root root 15666923 Nov  1 21:57 duplicity-full.20151101T215717Z.vol1.difftar
-rw-rw-rw- 1 root root  4966400 Nov  1 21:57 duplicity-full-signatures.20151101T215717Z.sigtar
-rw-rw-rw- 1 root root 27807454 Nov  1 23:41 test1
-rw-rw-rw- 1 root root 27807454 Nov  1 23:44 test2
-rw-rw-rw- 1 root root 27807454 Nov  1 23:52 test3
-rw-rw-rw- 1 root root 27807454 Nov  1 23:55 test4
-rw-rw-rw- 1 root root 27807454 Nov  1 23:38 webmin_1.770_all.deb

Interfaces                     │ RX bps       pps     %│ TX bps       pps     %
  lo                           │      0         0      │      0         0
 >eth0                         │   1.01KiB      2      │   1.10KiB      2
    qdisc none (pfifo_fast)    │      0         0      │   1.12KiB      2
───────────────────────────────┴───────────────────────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────
     KiB                      (RX Bytes/second)                                        MiB                      (TX Bytes/second)
  108.49 ..............|.............................................                 3.32 ........|||..||.............................................
   90.41 ..............|.............................................                 2.77 ......|||||||||.............................................
   72.33 .......|..|||||.............................................                 2.21 ......|||||||||.............................................
   54.25 ......|||||||||.............................................                 1.66 ......|||||||||.............................................
   36.16 ......|||||||||.............................................                 1.11 ......|||||||||.............................................
   18.08 ::::::|||||||||:::::::::::::::::::::::::::::::::::::::::::::                 0.55 ::::::|||||||||:::::::::::::::::::::::::::::::::::::::::::::
         1   5   10   15   20   25   30   35   40   45   50   55   60                      1   5   10   15   20   25   30   35   40   45   50   55   60

root@debian:~# /usr/local/bin/hubicfuse -d /mnt/hubic -o noauto_cache,sync_read,allow_other
!!! Authenticating... (client_id = 'api_hubic_yr1VyKkj76RRHLD4YXoZ6SsFN4KZXg8A')
....
....
FUSE library version: 2.9.3
nullpath_ok: 0
nopath: 0
utime_omit_ok: 0
unique: 1, opcode: INIT (26), nodeid: 0, insize: 56, pid: 0
INIT: 7.23
flags=0x0003f7fb
max_readahead=0x00020000
   INIT: 7.19
   flags=0x00000010
   max_readahead=0x00020000
   max_write=0x00020000
   max_background=0
   congestion_threshold=0
   unique: 1, success, outsize: 40
unique: 2, opcode: LOOKUP (1), nodeid: 1, insize: 47, pid: 25471
LOOKUP /backup
getattr /backup
* Hostname was NOT found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/?format=xml HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 200 OK
< Content-Length: 2337
< X-Account-Object-Count: 106037
< X-Account-Storage-Policy-Policy-0-Bytes-Used: 533705107252
< X-Account-Storage-Policy-Policy-0-Container-Count: 21
< X-Account-Meta-Quota: 13743895347200
< X-Timestamp: 1390691004.53621
< X-Account-Storage-Policy-Policy-0-Object-Count: 106037
< X-Account-Meta-Temp-Url-Key: K7YqxoYFsBE3
< X-Account-Bytes-Used: 533705107252
< X-Account-Container-Count: 21
< Content-Type: application/xml; charset=utf-8
< Accept-Ranges: bytes
< X-Trans-Id: 59896847:8E43_B221D521:01BB_5636A5F0_60603C8:3D90
< Date: Sun, 01 Nov 2015 23:53:20 GMT
< Connection: close
<
* Closing connection 0
!!! entry count: 21
   NODEID: 2
   unique: 2, success, outsize: 144
unique: 3, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 25471
LOOKUP /backup/test4
getattr /backup/test4
* Hostname was found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#1)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup?format=xml&delimiter=/&prefix= HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 200 OK
< Content-Length: 1701
< X-Container-Object-Count: 7
< Accept-Ranges: bytes
< X-Storage-Policy: Policy-0
< X-Container-Bytes-Used: 132170760
< X-Timestamp: 1446415036.73111
< Content-Type: application/xml; charset=utf-8
< X-Trans-Id: 59896847:8E44_B221D521:01BB_5636A5F0_FAD60F1:3D98
< Date: Sun, 01 Nov 2015 23:53:21 GMT
< Connection: close
<
* Closing connection 1
!!! entry count: 7
   unique: 3, error: -2 (No such file or directory), outsize: 16
unique: 4, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 25471
LOOKUP /backup/test4
getattr /backup/test4
   unique: 4, error: -2 (No such file or directory), outsize: 16
unique: 5, opcode: LOOKUP (1), nodeid: 2, insize: 46, pid: 25471
LOOKUP /backup/test4
getattr /backup/test4
   unique: 5, error: -2 (No such file or directory), outsize: 16
unique: 6, opcode: CREATE (35), nodeid: 2, insize: 62, pid: 25471
create flags: 0x80c1 /backup/test4 0100644 umask=0022
   create[139751390710496] flags: 0x80c1 /backup/test4
fgetattr[139751390710496] /backup/test4
   NODEID: 3
   unique: 6, success, outsize: 160
unique: 7, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 0 flags: 0x8001
   write[139751390710496] 131072 bytes to 0
   unique: 7, success, outsize: 24
unique: 8, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 131072 flags: 0x8001
   write[139751390710496] 131072 bytes to 131072
   unique: 8, success, outsize: 24
unique: 9, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 262144 flags: 0x8001
   write[139751390710496] 131072 bytes to 262144
   unique: 9, success, outsize: 24
unique: 10, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 393216 flags: 0x8001
   write[139751390710496] 131072 bytes to 393216
   unique: 10, success, outsize: 24
...
...
unique: 217, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 27525120 flags: 0x8001
   write[139751390710496] 131072 bytes to 27525120
   unique: 217, success, outsize: 24
unique: 218, opcode: WRITE (16), nodeid: 3, insize: 131152, pid: 25471
write[139751390710496] 131072 bytes to 27656192 flags: 0x8001
   write[139751390710496] 131072 bytes to 27656192
   unique: 218, success, outsize: 24
unique: 219, opcode: WRITE (16), nodeid: 3, insize: 20270, pid: 25471
write[139751390710496] 20190 bytes to 27787264 flags: 0x8001
   write[139751390710496] 20190 bytes to 27787264
   unique: 219, success, outsize: 24
unique: 220, opcode: FLUSH (25), nodeid: 3, insize: 64, pid: 25471
flush[139751390710496]
* Hostname was found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#2)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup_segments?format=xml&delimiter=/&prefix= HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 404 Not Found
< Content-Length: 70
< Content-Type: text/html; charset=UTF-8
< X-Trans-Id: 59896847:8E45_B221D521:01BB_5636A5F1_3EAB196:3D8E
< Date: Sun, 01 Nov 2015 23:53:21 GMT
< Connection: close
<
* Closing connection 2
* Hostname was found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#3)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup_segments?format=xml&delimiter=/&prefix= HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 404 Not Found
< Content-Length: 70
< Content-Type: text/html; charset=UTF-8
< X-Trans-Id: 59896847:8E46_B221D521:01BB_5636A5F9_E200E40:3D95
< Date: Sun, 01 Nov 2015 23:53:29 GMT
< Connection: close
<
* Closing connection 3
* Hostname was found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#4)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* old SSL session ID is stale, removing
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup_segments?format=xml&delimiter=/&prefix= HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 404 Not Found
< Content-Length: 70
< Content-Type: text/html; charset=UTF-8
< X-Trans-Id: 59896847:8E47_B221D521:01BB_5636A609_10229A92:3D99
< Date: Sun, 01 Nov 2015 23:53:46 GMT
< Connection: close
<
* Closing connection 4
* Hostname was found in DNS cache
*   Trying 178.33.213.33...
* Connected to lb1.hubic.ovh.net (178.33.213.33) port 443 (#5)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* old SSL session ID is stale, removing
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> GET /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup_segments?format=xml&delimiter=/&prefix= HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0

< HTTP/1.1 404 Not Found
< Content-Length: 70
< Content-Type: text/html; charset=UTF-8
< X-Trans-Id: 59896847:8E4A_B221D521:01BB_5636A62A_1070855A:3D9A
< Date: Sun, 01 Nov 2015 23:54:18 GMT
< Connection: close
<
* Closing connection 5
!!! entry count: 0
* Hostname was found in DNS cache
* Hostname in DNS cache was stale, zapped
*   Trying 37.59.191.74...
* Connected to lb1.hubic.ovh.net (37.59.191.74) port 443 (#6)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL re-using session ID
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* old SSL session ID is stale, removing
* Server certificate:
*        subject: OU=Domain Control Validated; CN=*.hubic.ovh.net
*        start date: 2014-09-29 12:09:39 GMT
*        expire date: 2017-09-29 12:09:39 GMT
*        subjectAltName: lb1.hubic.ovh.net matched
*        issuer: C=BE; O=GlobalSign nv-sa; CN=AlphaSSL CA - SHA256 - G2
*        SSL certificate verify ok.
> PUT /v1/AUTH_d84e61fb289c9183429efc89d943e735/backup/test4 HTTP/1.1
User-Agent: CloudFuse
Host: lb1.hubic.ovh.net
Accept: */*
X-Auth-Token: 66682276879e4f86a302d1b78b7dedd0
Content-Length: 27807454
Expect: 100-continue

< HTTP/1.1 100 Continue
* We are completely uploaded and fine
< HTTP/1.1 201 Created
< Last-Modified: Sun, 01 Nov 2015 23:55:23 GMT
< Content-Length: 0
< Etag: 00e73d0700178eaa3574aa182d61291b
< Content-Type: text/html; charset=UTF-8
< X-Trans-Id: 59896847:DE53_253BBF4A:01BB_5636A66A_5F99288:2899
< Date: Sun, 01 Nov 2015 23:55:32 GMT
< Connection: close
<
* Closing connection 6
   unique: 220, success, outsize: 16
unique: 221, opcode: RELEASE (18), nodeid: 3, insize: 64, pid: 0
release[139751390710496] flags: 0x8001
   unique: 221, success, outsize: 16

**Comment by dan-cristian** [comment]
I found a fix for this issue. The problem is that by default hubicfuse perform 4 retries after each failed GET attempt, and waits around 8 seconds or more between each retry.

edit cloudfsapi.c, go to line 31 and change from:
#define REQUEST_RETRIES 4
to
#define REQUEST_RETRIES 1

also go to line 280 and change from:
sleep(8 << tries); // backoff
to
sleep(1 << tries); // backoff

Copy will work way now much faster. I am not sure if this introduces additional issues, will test.

**Comment by TurboGit** [comment]
Sounds interesting indeed! Please keep us posted and I'll fix that in the code. Maybe with REQUEST_RETRIES to 2 though.

**Comment by dan-cristian** [comment]
this was also fixed by removing unnecessary retries when HTTP 404 code is received, and also by skipping request for segmented URLs on non-segmented files.
