### ISSUE TITLE
Segmentation fault when uploading/copy long file names & paths

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#88]
hubicfuse will crash on copy if the full path for a file is longer than ~250 characters. This is because a file with a long name is generated on the temp folder with name length longer than NAME_MAX constant which is usually set to 255.

the error is generated on cfs_create function:
snprintf(file_path, PATH_MAX, "%s/.cloudfuse%ld-%s", temp_dir, (long)getpid(), tmp_path);
above line will produce a very long file name.
temp_file = fopen(file_path, "w+b");
this will return NULL.
of->fd = dup(fileno(temp_file));
here we get the segmentation fault.

I implemented a quick and dirty fix here:
https://github.com/dan-cristian/hubicfuse/blob/utime/cloudfuse.c
but I'm not very happy with the solution, maybe someone can do  better one.

**Comment by TurboGit** [comment]
I would use the MD5 value of the path. I'll comment on your code.

**Comment by TurboGit** [comment]
Cannot annotate the file... So here it goes:

I will remove this mess:

<<<
    debugf("c1");
    char tmp_path[PATH_MAX];
    strncpy(tmp_path, path, PATH_MAX);
    debugf("c2");
    char *pch;
    while((pch = strchr(tmp_path, '/'))) {
      *pch = '.';
    }
    debugf("c3");
    char file_path[PATH_MAX];
>>>

I'll compute the MD5 sum of path variable say in md5_path and write:

snprintf(file_path, PATH_MAX, "%s/.cloudfuse%ld-%s", temp_dir, (long)getpid(), md5_path);

This should be sufficient to avoid name conflicts and avoid the too long name indeed!

**Comment by TurboGit** [comment]
Let me know, I can look at this if you like.

**Comment by dan-cristian** [comment]
agreed, that was the solution I was thinking of, I'll add it in my branch, thanks.
I'l still keep the debug bits until the branch is merged to master.

**Comment by TurboGit** [comment]
Perfect!

**Comment by dan-cristian** [comment]
I have completed the fix, can be located in my work in progress forked branch: https://github.com/dan-cristian/hubicfuse/tree/utime.

I decided to keep the original file prefix and append at the end the MD5 hashe id, up to the maximum allowed file name length. This way it is easier to identify in the cache the original file name.

This branch has multiple other improvements, if someone is interested only in this fix let me know and I'll post it separately.

**Comment by TurboGit** [comment]
Ok, do not hesitate to send a merge-request when ready.

**Comment by dan-cristian** [comment]
Merge request sent

**Comment by TurboGit** [comment]
See my comments on the merge request.

**Comment by TurboGit** [comment]
Should be fixed now.
