### ISSUE TITLE
hubicfuse command stalled, no give prompt back and not mounting

### ISSUE THREAD

**Issue by nephaste** [TurboGit/hubicfuse#90]
just compiled hubicfuse for Qnap x86 NAS

libs =
openssl 1.01p
fuse 2.9.4
json-c 0.12
Culr 7.45
files 5.22 (libmagic)
libxml 2.9.2
libidn 1.29

well created .hubicfuse in /root
helped with script hubic_token

created /mnt/hubic

but when i launch hubicfuse /mnt/hubic -o noauto_cache,sync_read,allow_other
it stalled without giving back the prompt (like a no dameon like app) and no effect

nothing in /mnt/hubic

ldd output =

[/opt/HubicFS/bin] # ldd hubicfuse
        linux-gate.so.1 =>  (0xf777c000)
        libxml2.so.2 => /opt/HubicFS/lib/libxml2.so.2 (0xf763d000)
        libcurl.so.4 => /opt/HubicFS/lib/libcurl.so.4 (0xf75e1000)
        libfuse.so.2 => /opt/HubicFS/lib/libfuse.so.2 (0xf75b3000)
        libssl.so.1.0.0 => /opt/HubicFS/lib/libssl.so.1.0.0 (0xf7551000)
        libcrypto.so.1.0.0 => /opt/HubicFS/lib/libcrypto.so.1.0.0 (0xf73c4000)
        libjson-c.so.2 => /opt/HubicFS/lib/libjson-c.so.2 (0xf73b9000)
        libmagic.so.1 => /opt/HubicFS/lib/libmagic.so.1 (0xf7398000)
        libpthread.so.0 => /lib/libpthread.so.0 (0xf7379000)
        libc.so.6 => /lib/libc.so.6 (0xf7246000)
        librt.so.1 => /lib/librt.so.1 (0xf723d000)
        libdl.so.2 => /lib/libdl.so.2 (0xf7239000)
        libz.so.1 => /opt/HubicFS/lib/libz.so.1 (0xf7221000)
        libiconv.so.2 => /opt/HubicFS/lib/libiconv.so.2 (0xf7140000)
        libm.so.6 => /lib/libm.so.6 (0xf711a000)
        libidn.so.11 => /opt/HubicFS/lib/libidn.so.11 (0xf70e8000)
        /lib/ld-linux.so.2 (0xf777d000)

more funny when .hubicfuse is not in /root

[/opt/HubicFS/bin] # ./hubicfuse
Unable to determine client_id, client_secret or refresh_token.

These can be set either as mount options or in a file named /root/.hubicfuse

  client_id=[App's id]
  client_secret=[App's secret]
  refresh_token=[Get it running hubic_token]
The following settings are optional:

  cache_timeout=[Seconds for directory caching, default 600]
  verify_ssl=[False to disable SSL cert verification]
  segment_size=[Size to use when creating DLOs, default 1073741824]
  segment_above=[File size at which to use segments, defult 2147483648]
  storage_url=[Storage URL for other tenant to view container]
  container=[Public container to view of tenant specified by storage_url]
  temp_dir=[Directory to store temp files]

I am lost anyone has idea ???? look like the .hubicfuse is not reading correctly or making application loops.

i just past and copy the output from the script hubicfuse_token

**Comment by nephaste** [comment]
just found adding 

verify_ssl=False

do the trick.... what is it related ? is this because ca.cert are missing in /etc/ssl ???

**Comment by TurboGit** [comment]
A possible explanation indeed.
