### ISSUE TITLE
Large files (segmented) are shown with size 0

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#91]
Large files appear with size 0 after running the ls -al command on a hubic mounted folder that has large files (which are segmented).

The issue appears because on first folder access hubicfuse only reads file metadata, and segmented files are uploaded on the cloud with 0 file size. The content is stored on a subfolder with _segment suffix.

This creates multiple problems, for example when copying files with "update if file size is different" option, the whole file will be first downloaded, then uploaded again, even if the content is the same. this results in a very poor performance on sync.

**Comment by TurboGit** [comment]
Closing as now fixed.
