### ISSUE TITLE
No such file or directory error when cache expires

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#92]
During a long file copy operation the cache will expire and a No such file or directory error will be thrown by cfs_getattr() function in cloudfuse.c (maybe also by other operations).

This makes the upload process to cloud unreliable.

A quick fix is to set a very large cache_timeout value in .hubicfuse config file.

**Comment by dan-cristian** [comment]
I think I fixed this in my forked branch: https://github.com/dan-cristian/hubicfuse

**Comment by TurboGit** [comment]
Closing as now fixed.
