### ISSUE TITLE
Cannot use Hubicfuse on Raspberry Pi using Debian Weezy

### ISSUE THREAD

**Issue by raybus** [TurboGit/hubicfuse#93]
Hi!

I am very interested in using HubicFuse with my Raspberry Pi to mount my Hubicspace without constant syncing. But when I try to use the apt-get install option mentioned in your manual I get the error:
Unable to locate package libjson-c-dev

As a complete Linuxnoob... What can I do to fix this?

**Comment by flotho** [comment]
Hi @raybus 
I have exactly the same issue here.
The problem is that for wheezy it's a backport : https://packages.debian.org/fr/wheezy-backports/libjson-c-dev

**Comment by raybus** [comment]
Hi @flotho 
A colleague mentioned that Raspbian Jessie does support this package, so I will give it a try. 
Thanks for you answer!

**Comment by phavekes** [comment]
Must be a clever colleague :-) 

Did it work @raybus?

**Comment by raybus** [comment]
Hi phavekes!

It is a clever colleague! 
And yes it works, I can now directly mount via the Pi to my Hubic cloud storage. 
I also managed to install an FTP-server on the Pi. I will make a new thread for my problems I have when I upload or download via the ftp-server...
