### ISSUE TITLE
Rename does not work on file paths longer than 256 characters

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#95]
When doing a rename (mv) operation with destination file residing on a folder with full path longer than 256 chars I get HTTP 400 error with message ~ "X-Object-Meta-FilePath size larger than 256 characters".

**Comment by dan-cristian** [comment]
This was also fixed in the last commit, see coudfsapi.c/add_header() function.

**Comment by TurboGit** [comment]
So closing! Great!
