### ISSUE TITLE
error playing a video from samba sharing a fuse mount

### ISSUE THREAD

**Issue by dan-cristian** [TurboGit/hubicfuse#99]
I have shared a hubic mount via samba and tried to play a video file using several players (VLC, Windows Media Player), without success.
I am able to copy the file from the samba share succesfully, however video playing does not work, even when the file is already cached.

Any thoughts on why this is not working?

**Comment by dan-cristian** [comment]
I have resolved this, the problem was that cfs_open function set the opened file as non-seekable.

In cloudfuse.c, cfs_open function, change this line to:
info->nonseekable = 0;
 and should work.

if it doesn't, enable also raw read/write access in samba (smb.conf)

**Comment by dragetd** [comment]
Is there a reason why files are marked as not seekable? Simply opening them as seekable sounds like a deep change. Any idea what consequences this has? And if it works, why not implement it in the main code?

**Comment by dan-cristian** [comment]
I use hubicfuse with files marked as seekable for a while now and did not encountered any issue. I suggest changing the main code as per above patch.

**Comment by dragetd** [comment]
I am still trying to understand / read through the code. If files are cached locally, seeking and writing might mess up the syncing. But instead of trying to understand it, I will try to apply your patch and run some tests. :)

**Comment by TurboGit** [comment]
@dan-cristian ok will do that then.

**Comment by TurboGit** [comment]
Done and committed. Forgot to mention the issue no. Anyway let's close this at this stage.
